import {BadRequestException,Body,Controller,Delete,Get,Headers,Module,Param,Patch,Post,Query} from '@nestjs/common';
import {z} from 'zod';
import {Db} from './db.js';
import {AccessService,verifyUserJwt} from './security.js';
import {AuthAdminService} from './auth-admin.js';

const uuid=z.string().uuid();const status=z.enum(['active','paused','archived']);const clientRole=z.enum(['owner','manager','editor','viewer']);const clientUserStatus=z.enum(['invited','active','suspended']);
const clientSchema=z.object({agencyId:uuid,company:z.string().trim().min(1).max(160),url:z.string().url().nullable().optional(),timezone:z.string().min(1).default('Asia/Almaty'),country:z.string().max(80).nullable().optional(),language:z.string().max(12).default('ru'),currency:z.string().max(8).default('KZT'),startDate:z.string().date().nullable().optional(),logoUrl:z.string().url().nullable().optional(),brandColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default('#0072EE'),status:status.default('active'),industry:z.string().max(120).nullable().optional(),groupId:uuid.nullable().optional(),accountManagerId:uuid.nullable().optional(),contacts:z.array(z.record(z.string(),z.unknown())).default([]),goals:z.string().max(5000).default(''),notes:z.string().max(10000).default(''),analyticsSettings:z.record(z.string(),z.unknown()).default({}),attributionSettings:z.record(z.string(),z.unknown()).default({}),trackingSettings:z.record(z.string(),z.unknown()).default({}),retentionDays:z.number().int().min(30).max(3650).default(730),agencyMarkup:z.number().min(0).max(10000).default(0),tags:z.array(z.string().trim().min(1).max(60)).max(50).default([])});
const updateClientSchema=clientSchema.partial().extend({agencyId:uuid});
const groupSchema=z.object({agencyId:uuid,name:z.string().trim().min(1).max(100),description:z.string().max(2000).default(''),color:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default('#64748B')});
const updateGroupSchema=groupSchema.partial().extend({agencyId:uuid});
const inviteSchema=z.object({agencyId:uuid,email:z.string().trim().email(),role:clientRole.default('viewer'),permissions:z.array(z.string()).default(['client.read']),redirectTo:z.string().url().optional()});
const updateUserSchema=z.object({agencyId:uuid,role:clientRole.optional(),status:clientUserStatus.optional(),permissions:z.array(z.string()).optional()});
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const result=schema.safeParse(value);if(!result.success)throw new BadRequestException(result.error.flatten());return result.data};
const selectClient=`select c.*,g.name group_name,p.name account_manager_name from public.clients c left join public.client_groups g on g.id=c.group_id left join public.user_profiles p on p.user_id=c.account_manager_id`;

@Controller('health')class HealthController{@Get()health(){return{ok:true,service:'clients-api'}}}

@Controller('v1/clients')
class ClientsController{constructor(private db:Db,private access:AccessService){}
@Get()async list(@Headers('authorization')a:string,@Query('agencyId')agencyId:string,@Query('search')search?:string,@Query('status')s?:string,@Query('groupId')groupId?:string){const u=await verifyUserJwt(a);parse(uuid,agencyId);await this.access.require(u.userId,agencyId,'clients.read');const values:unknown[]=[agencyId];const where=['c.agency_id=$1'];if(search?.trim()){values.push(`%${search.trim()}%`);where.push(`(c.company ilike $${values.length} or coalesce(c.url,'') ilike $${values.length})`)}if(s){values.push(parse(status,s));where.push(`c.status=$${values.length}`)}if(groupId){values.push(parse(uuid,groupId));where.push(`c.group_id=$${values.length}`)}const r=await this.db.query(`${selectClient} where ${where.join(' and ')} order by c.company limit 500`,values);return{items:r.rows}}
@Get(':id')async get(@Headers('authorization')a:string,@Param('id')id:string,@Query('agencyId')agencyId:string){const u=await verifyUserJwt(a);parse(uuid,id);parse(uuid,agencyId);await this.access.require(u.userId,agencyId,'clients.read');const r=await this.db.query(`${selectClient} where c.id=$1 and c.agency_id=$2`,[id,agencyId]);if(!r.rows[0])throw new BadRequestException('CLIENT_NOT_FOUND');return r.rows[0]}
@Post()async create(@Headers('authorization')a:string,@Body()body:unknown){const u=await verifyUserJwt(a);const x=parse(clientSchema,body);await this.access.require(u.userId,x.agencyId,'clients.manage');const r=await this.db.query(`insert into public.clients(agency_id,company,url,timezone,country,language,currency,start_date,logo_url,brand_color,status,industry,group_id,account_manager_id,contacts,goals,notes,analytics_settings,attribution_settings,tracking_settings,retention_days,agency_markup,tags) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23) returning *`,[x.agencyId,x.company,x.url??null,x.timezone,x.country??null,x.language,x.currency,x.startDate??null,x.logoUrl??null,x.brandColor,x.status,x.industry??null,x.groupId??null,x.accountManagerId??null,x.contacts,x.goals,x.notes,x.analyticsSettings,x.attributionSettings,x.trackingSettings,x.retentionDays,x.agencyMarkup,x.tags]);return r.rows[0]}
@Patch(':id')async update(@Headers('authorization')a:string,@Param('id')id:string,@Body()body:unknown){const u=await verifyUserJwt(a);parse(uuid,id);const x=parse(updateClientSchema,body);await this.access.require(u.userId,x.agencyId,'clients.manage');const current=await this.db.query<any>('select * from public.clients where id=$1 and agency_id=$2',[id,x.agencyId]);if(!current.rows[0])throw new BadRequestException('CLIENT_NOT_FOUND');const c=current.rows[0];const r=await this.db.query(`update public.clients set company=$3,url=$4,timezone=$5,country=$6,language=$7,currency=$8,start_date=$9,logo_url=$10,brand_color=$11,status=$12,industry=$13,group_id=$14,account_manager_id=$15,contacts=$16,goals=$17,notes=$18,analytics_settings=$19,attribution_settings=$20,tracking_settings=$21,retention_days=$22,agency_markup=$23,tags=$24 where id=$1 and agency_id=$2 returning *`,[id,x.agencyId,x.company??c.company,x.url===undefined?c.url:x.url,x.timezone??c.timezone,x.country===undefined?c.country:x.country,x.language??c.language,x.currency??c.currency,x.startDate===undefined?c.start_date:x.startDate,x.logoUrl===undefined?c.logo_url:x.logoUrl,x.brandColor??c.brand_color,x.status??c.status,x.industry===undefined?c.industry:x.industry,x.groupId===undefined?c.group_id:x.groupId,x.accountManagerId===undefined?c.account_manager_id:x.accountManagerId,x.contacts??c.contacts,x.goals??c.goals,x.notes??c.notes,x.analyticsSettings??c.analytics_settings,x.attributionSettings??c.attribution_settings,x.trackingSettings??c.tracking_settings,x.retentionDays??c.retention_days,x.agencyMarkup??c.agency_markup,x.tags??c.tags]);return r.rows[0]}
@Delete(':id')async remove(@Headers('authorization')a:string,@Param('id')id:string,@Query('agencyId')agencyId:string){const u=await verifyUserJwt(a);await this.access.require(u.userId,agencyId,'clients.manage');await this.db.query(`update public.clients set status='archived' where id=$1 and agency_id=$2`,[parse(uuid,id),parse(uuid,agencyId)]);return{ok:true}}}

@Controller('v1/client-groups')
class GroupsController{constructor(private db:Db,private access:AccessService){}
@Get()async list(@Headers('authorization')a:string,@Query('agencyId')agencyId:string){const u=await verifyUserJwt(a);await this.access.require(u.userId,agencyId,'clients.read');const r=await this.db.query(`select g.*,count(c.id)::int client_count from public.client_groups g left join public.clients c on c.group_id=g.id where g.agency_id=$1 group by g.id order by g.name`,[parse(uuid,agencyId)]);return{items:r.rows}}
@Post()async create(@Headers('authorization')a:string,@Body()body:unknown){const u=await verifyUserJwt(a);const x=parse(groupSchema,body);await this.access.require(u.userId,x.agencyId,'clients.manage');const r=await this.db.query(`insert into public.client_groups(agency_id,name,description,color,created_by) values($1,$2,$3,$4,$5) returning *`,[x.agencyId,x.name,x.description,x.color,u.userId]);return r.rows[0]}
@Patch(':id')async update(@Headers('authorization')a:string,@Param('id')id:string,@Body()body:unknown){const u=await verifyUserJwt(a);const x=parse(updateGroupSchema,body);await this.access.require(u.userId,x.agencyId,'clients.manage');const current=await this.db.query<any>('select * from public.client_groups where id=$1 and agency_id=$2',[parse(uuid,id),x.agencyId]);if(!current.rows[0])throw new BadRequestException('CLIENT_GROUP_NOT_FOUND');const g=current.rows[0];const r=await this.db.query(`update public.client_groups set name=$3,description=$4,color=$5 where id=$1 and agency_id=$2 returning *`,[id,x.agencyId,x.name??g.name,x.description??g.description,x.color??g.color]);return r.rows[0]}
@Delete(':id')async remove(@Headers('authorization')a:string,@Param('id')id:string,@Query('agencyId')agencyId:string){const u=await verifyUserJwt(a);await this.access.require(u.userId,agencyId,'clients.manage');const result=await this.db.query(`delete from public.client_groups where id=$1 and agency_id=$2 and not exists(select 1 from public.clients where group_id=$1) returning id`,[parse(uuid,id),parse(uuid,agencyId)]);if(!result.rows[0])throw new BadRequestException('CLIENT_GROUP_NOT_EMPTY_OR_NOT_FOUND');return{ok:true}}}

@Controller('v1/clients/:clientId/users')
class UsersController{constructor(private db:Db,private access:AccessService,private authAdmin:AuthAdminService){}
@Get()async list(@Headers('authorization')a:string,@Param('clientId')clientId:string,@Query('agencyId')agencyId:string){const u=await verifyUserJwt(a);await this.access.require(u.userId,agencyId,'client_users.read');const r=await this.db.query(`select cu.*,up.name,au.email from public.client_users cu left join public.user_profiles up on up.user_id=cu.user_id left join auth.users au on au.id=cu.user_id join public.clients c on c.id=cu.client_id where cu.client_id=$1 and c.agency_id=$2 order by cu.created_at`,[parse(uuid,clientId),parse(uuid,agencyId)]);return{items:r.rows}}
@Post()async invite(@Headers('authorization')a:string,@Param('clientId')clientId:string,@Body()body:unknown){const u=await verifyUserJwt(a);const x=parse(inviteSchema,body);await this.access.require(u.userId,x.agencyId,'client_users.manage');const client=await this.db.query('select id from public.clients where id=$1 and agency_id=$2',[parse(uuid,clientId),x.agencyId]);if(!client.rows[0])throw new BadRequestException('CLIENT_NOT_FOUND');let target=await this.authAdmin.findUserByEmail(x.email);let invited=false;if(!target){target=await this.authAdmin.invite(x.email,x.redirectTo);invited=true}if(!target.id)throw new BadRequestException('INVITED_USER_ID_MISSING');const r=await this.db.query(`insert into public.client_users(client_id,user_id,role,status,permissions,invited_by) values($1,$2,$3,$4,$5,$6) on conflict(client_id,user_id) do update set role=excluded.role,status=excluded.status,permissions=excluded.permissions,updated_at=now() returning *`,[clientId,target.id,x.role,invited?'invited':'active',x.permissions,u.userId]);return{...r.rows[0],email:x.email,invitationSent:invited}}
@Patch(':userId')async update(@Headers('authorization')a:string,@Param('clientId')clientId:string,@Param('userId')userId:string,@Body()body:unknown){const u=await verifyUserJwt(a);const x=parse(updateUserSchema,body);await this.access.require(u.userId,x.agencyId,'client_users.manage');const current=await this.db.query<any>(`select cu.* from public.client_users cu join public.clients c on c.id=cu.client_id where cu.client_id=$1 and cu.user_id=$2 and c.agency_id=$3`,[parse(uuid,clientId),parse(uuid,userId),x.agencyId]);if(!current.rows[0])throw new BadRequestException('CLIENT_USER_NOT_FOUND');const member=current.rows[0];const r=await this.db.query(`update public.client_users set role=$4,status=$5,permissions=$6,updated_at=now() where client_id=$1 and user_id=$2 returning *`,[clientId,userId,x.agencyId,x.role??member.role,x.status??member.status,x.permissions??member.permissions]);return r.rows[0]}
@Delete(':userId')async remove(@Headers('authorization')a:string,@Param('clientId')clientId:string,@Param('userId')userId:string,@Query('agencyId')agencyId:string){const u=await verifyUserJwt(a);await this.access.require(u.userId,agencyId,'client_users.manage');await this.db.query(`delete from public.client_users cu using public.clients c where cu.client_id=$1 and cu.user_id=$2 and c.id=cu.client_id and c.agency_id=$3`,[parse(uuid,clientId),parse(uuid,userId),parse(uuid,agencyId)]);return{ok:true}}}

@Module({controllers:[HealthController,ClientsController,GroupsController,UsersController],providers:[Db,AccessService,AuthAdminService]})export class AppModule{}
