import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import type {Session} from '@supabase/supabase-js';
import type {WorkspaceBootstrap} from '@imds/api-client';
import {getCurrentSession,hasSupabaseEnvironment,loadWorkspaceBootstrap,onAuthStateChange,signInWithPassword,signOut} from '@imds/auth';
import {useI18n} from '../i18n/I18nProvider';

type AuthState={configured:boolean;loading:boolean;session:Session|null;workspace:WorkspaceBootstrap|null;error:string|null;signIn:(email:string,password:string)=>Promise<void>;signOut:()=>Promise<void>;switchAgency:(agencyId:string)=>Promise<void>;refresh:()=>Promise<void>};
const AuthContext=createContext<AuthState|null>(null);

export function AuthProvider({children}:{children:ReactNode}){const{t}=useI18n();const configured=hasSupabaseEnvironment();const[loading,setLoading]=useState(true);const[session,setSession]=useState<Session|null>(null);const[workspace,setWorkspace]=useState<WorkspaceBootstrap|null>(null);const[error,setError]=useState<string|null>(null);const localizeError=(value:unknown,fallbackKey:string)=>{const message=value instanceof Error?value.message.toLowerCase():'';if(message.includes('invalid login')||message.includes('invalid credentials'))return t('auth.errors.invalidCredentials');if(message.includes('email not confirmed'))return t('auth.errors.emailNotConfirmed');if(message.includes('network')||message.includes('fetch'))return t('common.networkError');return t(fallbackKey)};const hydrate=async(activeAgencyId?:string|null)=>{setLoading(true);setError(null);try{const nextSession=await getCurrentSession();setSession(nextSession);if(configured&&!nextSession){setWorkspace(null);return}setWorkspace(await loadWorkspaceBootstrap(activeAgencyId))}catch(value){setError(localizeError(value,'auth.errors.workspaceLoad'));setWorkspace(null)}finally{setLoading(false)}};useEffect(()=>{void hydrate();return onAuthStateChange(next=>{setSession(next);void hydrate()})},[t]);const value=useMemo<AuthState>(()=>({configured,loading,session,workspace,error,signIn:async(email,password)=>{setLoading(true);setError(null);try{await signInWithPassword(email,password);await hydrate()}catch(value){setError(localizeError(value,'auth.errors.signIn'));setLoading(false);throw value}},signOut:async()=>{await signOut();setSession(null);setWorkspace(null)},switchAgency:async agencyId=>hydrate(agencyId),refresh:()=>hydrate(workspace?.activeAgency?.id)}),[configured,loading,session,workspace,error,t]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error('useAuth must be used inside AuthProvider');return value}
