import {createClient,type Session,type SupabaseClient} from '@supabase/supabase-js';
import {getDemoBootstrap,type WorkspaceBootstrap} from '@imds/api-client';
let browserClient:SupabaseClient|null=null;
export function hasSupabaseEnvironment(){return Boolean(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)}
export function getSupabaseBrowserClient(){if(browserClient)return browserClient;const url=import.meta.env.VITE_SUPABASE_URL;const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('Supabase environment is not configured');browserClient=createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return browserClient}
export async function getCurrentSession():Promise<Session|null>{if(!hasSupabaseEnvironment())return null;const{data,error}=await getSupabaseBrowserClient().auth.getSession();if(error)throw error;return data.session}
export function onAuthStateChange(callback:(session:Session|null)=>void){if(!hasSupabaseEnvironment())return()=>{};const{data}=getSupabaseBrowserClient().auth.onAuthStateChange((_event:string,session:Session|null)=>callback(session));return()=>data.subscription.unsubscribe()}
export async function signInWithPassword(email:string,password:string){const{error}=await getSupabaseBrowserClient().auth.signInWithPassword({email,password});if(error)throw error}
export async function signOut(){if(hasSupabaseEnvironment()){const{error}=await getSupabaseBrowserClient().auth.signOut();if(error)throw error}}
export async function loadWorkspaceBootstrap(activeAgencyId?:string|null):Promise<WorkspaceBootstrap>{if(!hasSupabaseEnvironment())return getDemoBootstrap(activeAgencyId);const client=getSupabaseBrowserClient();const{data:sessionData,error:sessionError}=await client.auth.getSession();if(sessionError)throw sessionError;if(!sessionData.session)throw new Error('AUTH_REQUIRED');const{data,error}=await client.rpc('workspace_bootstrap',{target_agency_id:activeAgencyId??null});if(error)throw error;if(!data)throw new Error('Workspace bootstrap returned no data');return{...(data as WorkspaceBootstrap),mode:'supabase'}}
