import {createClient,type Session,type SupabaseClient} from '@supabase/supabase-js';
import {getDemoBootstrap,type WorkspaceBootstrap} from '@imds/api-client';
let browserClient:SupabaseClient|null=null;
export function hasSupabaseEnvironment(){return Boolean(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)}
export function getSupabaseBrowserClient(){if(browserClient)return browserClient;const url=import.meta.env.VITE_SUPABASE_URL;const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('Supabase environment is not configured');browserClient=createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return browserClient}
export async function getCurrentSession():Promise<Session|null>{if(!hasSupabaseEnvironment())return null;const{data,error}=await getSupabaseBrowserClient().auth.getSession();if(error)throw error;return data.session}
export function onAuthStateChange(callback:(session:Session|null,event:string)=>void){if(!hasSupabaseEnvironment())return()=>{};const{data}=getSupabaseBrowserClient().auth.onAuthStateChange((event:string,session:Session|null)=>callback(session,event));return()=>data.subscription.unsubscribe()}
export async function signInWithPassword(email:string,password:string){const{error}=await getSupabaseBrowserClient().auth.signInWithPassword({email,password});if(error)throw error}
export async function signInWithMagicLink(email:string,redirectTo:string){const{error}=await getSupabaseBrowserClient().auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo,shouldCreateUser:false}});if(error)throw error}
export async function requestPasswordReset(email:string,redirectTo:string){const{error}=await getSupabaseBrowserClient().auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error}
export async function updatePassword(password:string){const{error}=await getSupabaseBrowserClient().auth.updateUser({password});if(error)throw error}
export async function refreshCurrentSession(){const{data,error}=await getSupabaseBrowserClient().auth.refreshSession();if(error)throw error;return data.session}
export async function signOut(scope:'local'|'global'='local'){if(hasSupabaseEnvironment()){const{error}=await getSupabaseBrowserClient().auth.signOut({scope});if(error)throw error}}
export async function setWorkspaceContext(agencyId:string,clientId?:string|null){if(!hasSupabaseEnvironment())return{activeAgencyId:agencyId,activeClientId:clientId??null};const{data,error}=await getSupabaseBrowserClient().rpc('set_workspace_context',{target_agency_id:agencyId,target_client_id:clientId??null});if(error)throw error;return data as {activeAgencyId:string;activeClientId:string|null}}
export async function loadWorkspaceBootstrap(activeAgencyId?:string|null):Promise<WorkspaceBootstrap>{if(!hasSupabaseEnvironment())return getDemoBootstrap(activeAgencyId);const client=getSupabaseBrowserClient();const{data:sessionData,error:sessionError}=await client.auth.getSession();if(sessionError)throw sessionError;if(!sessionData.session)throw new Error('AUTH_REQUIRED');const{data,error}=await client.rpc('workspace_bootstrap',{target_agency_id:activeAgencyId??null});if(error)throw error;if(!data)throw new Error('Workspace bootstrap returned no data');return{...(data as WorkspaceBootstrap),mode:'supabase'}}
