import {useMemo,useState,type ReactNode}from'react';
import{Link,useParams}from'@tanstack/react-router';
import{useQuery,useQueryClient}from'@tanstack/react-query';
import{connectorCatalog,connectorCategories,type ConnectorCategory,type ConnectorAuthType,type ConnectorLifecycle}from'@imds/integrations';
import{getSupabaseBrowserClient,hasSupabaseEnvironment}from'@imds/auth';
import{useAuth}from'../../app/AuthProvider';
import{ConnectDataSourceModal}from'../../components/ConnectDataSourceModal';
import{integrationApi}from'../../integration-api';
import{IntegrationBrandMark,integrationBrandStyle}from'./IntegrationBrandMark';
import'./integrations-workspace.css';

type View='catalog'|'connections'|'agency'|'client'|'schema'|'health';
type Integration={id:string;slug:string;name:string;category:ConnectorCategory;authType:ConnectorAuthType;lifecycle:ConnectorLifecycle;isBeta:boolean;isNew:boolean;isPopular:boolean};
type Source={id:string;client_id:string;integration_id:string;account_id:string|null;label:string;external_identifier:string;status:string;last_sync_at:string|null;sync_error:any;settings:Record<string,any>};
type Account={id:string;integration_id:string;label:string;external_account_id:string|null;status:string;expires_at:string|null};
type Job={id:string;data_source_id:string;period_from:string;period_to:string;state:string;attempts:number;max_attempts:number;run_after:string;last_error:any};
type Run={id:string;data_source_id:string;state:string;started_at:string;finished_at:string|null;rows_fetched:number;rows_written:number;error:any};
type Data={mode:'live'|'local';integrations:Integration[];sources:Source[];accounts:Account[];jobs:Job[];runs:Run[]};
const categories:('all'|ConnectorCategory)[]=['all','analytics','paid_ads','seo','social','ecommerce','email','call_tracking','local','database'];
const schema:Record<string,string[]>={'google-ads':['account','campaign','ad group','ad','impressions','clicks','spend','conversions'],'ga4':['property','campaign','source','medium','sessions','users','conversions','revenue'],'search-console':['site','query','page','country','device','clicks','impressions','position'],'meta-ads':['account','campaign','ad set','ad','impressions','clicks','spend','leads'],'tiktok-ads':['advertiser','campaign','ad group','ad','impressions','clicks','spend','conversions']};
const date=(v?:string|null)=>v?new Date(v).toLocaleString('ru-RU'):'—';
const err=(v:any)=>v?.message||v?.error_description||(v?JSON.stringify(v):'—');
const sourceStatus=(s:Source)=>s.settings?.paused?'paused':s.settings?.disconnected?'disconnected':s.status;
const tone=(s:string)=>['connected','succeeded'].includes(s)?'ok':['error','failed'].includes(s)?'bad':['queued','running','syncing'].includes(s)?'run':['paused','cancelled'].includes(s)?'warn':'off';

async function load(agencyId?:string):Promise<Data>{
 if(!hasSupabaseEnvironment()||!agencyId)return{mode:'local',integrations:connectorCatalog.map(x=>({id:`local:${x.slug}`,...x,isBeta:!!x.isBeta,isNew:!!x.isNew,isPopular:!!x.isPopular})),sources:[],accounts:[],jobs:[],runs:[]};
 const c=getSupabaseBrowserClient();
 const [i,s,a,j,r]=await Promise.all([
  c.from('integrations').select('id,slug,name,category,auth_type,lifecycle,is_beta,is_new,is_popular').order('sort_order'),
  c.from('data_sources').select('id,client_id,integration_id,account_id,label,external_identifier,status,last_sync_at,sync_error,settings').eq('agency_id',agencyId).order('created_at',{ascending:false}),
  c.from('data_source_accounts').select('id,integration_id,label,external_account_id,status,expires_at').eq('agency_id',agencyId).order('created_at',{ascending:false}),
  c.from('sync_jobs').select('id,data_source_id,period_from,period_to,state,attempts,max_attempts,run_after,last_error').eq('agency_id',agencyId).order('created_at',{ascending:false}).limit(100),
  c.from('sync_runs').select('id,data_source_id,state,started_at,finished_at,rows_fetched,rows_written,error').eq('agency_id',agencyId).order('started_at',{ascending:false}).limit(100),
 ]);
 const failure=i.error||s.error||a.error||j.error||r.error;if(failure)throw failure;
 return{mode:'live',integrations:(i.data||[]).map((x:any)=>({id:x.id,slug:x.slug,name:x.name,category:x.category,authType:x.auth_type,lifecycle:x.lifecycle,isBeta:!!x.is_beta,isNew:!!x.is_new,isPopular:!!x.is_popular})),sources:(s.data||[])as Source[],accounts:(a.data||[])as Account[],jobs:(j.data||[])as Job[],runs:(r.data||[])as Run[]};
}
function Pill({value}:{value:string}){return <span className={`ids-pill ${tone(value)}`}>{value}</span>}
function Head({title,text,action}:{title:string;text:string;action?:ReactNode}){return <header className="ids-head"><div><small>Integrations and Data Sources</small><h2>{title}</h2><p>{text}</p></div>{action}</header>}

export function IntegrationsWorkspacePage({view}:{view:View}){
 const{workspace}=useAuth();const params=useParams({strict:false})as{clientId?:string};const agencyId=workspace?.activeAgency?.id;const activeClient=params.clientId||workspace?.activeClientId||workspace?.clients[0]?.id;const qc=useQueryClient();
 const q=useQuery({queryKey:['ids',agencyId],queryFn:()=>load(agencyId),refetchInterval:view==='health'?15000:false});const d=q.data||{mode:'local',integrations:[],sources:[],accounts:[],jobs:[],runs:[]}as Data;
 const byIntegration=useMemo(()=>new Map(d.integrations.map(x=>[x.id,x])),[d.integrations]);const bySource=useMemo(()=>new Map(d.sources.map(x=>[x.id,x])),[d.sources]);const clients=useMemo(()=>new Map((workspace?.clients||[]).map(x=>[x.id,x.company])),[workspace]);
 const[query,setQuery]=useState(''),[category,setCategory]=useState<'all'|ConnectorCategory>('all'),[selected,setSelected]=useState<Integration|null>(null),[pending,setPending]=useState(''),[notice,setNotice]=useState('');
 const refresh=()=>qc.invalidateQueries({queryKey:['ids',agencyId]});
 const act=(key:string,ok:string,work:()=>Promise<any>)=>{setPending(key);setNotice('');void work().then(async()=>{await refresh();setNotice(ok)}).catch(e=>setNotice(e.message||'Action failed')).finally(()=>setPending(''))};
 const tabs:[View,string,string][]=[['catalog','Catalog','/data'],['connections','Connections','/data/connections'],['agency','Agency Connections','/data/agency-connections'],['client','Data Sources',activeClient?`/client/${activeClient}/data`:'/data/connections'],['schema','Schema','/data/schema'],['health','Sync Health','/data/sync-health']];
 const actions=(s:Source)=>{const status=sourceStatus(s),integration=byIntegration.get(s.integration_id),busy=!!pending;return <div className="ids-actions">{!['paused','disconnected'].includes(status)&&<button disabled={busy||status==='syncing'} onClick={()=>act(`sync:${s.id}`,'Sync queued',()=>integrationApi.sync(s.id))}>Sync now</button>}{status==='paused'?<button disabled={busy} onClick={()=>act(`resume:${s.id}`,'Resumed',()=>integrationApi.setStatus(s.id,'resume'))}>Resume</button>:status!=='disconnected'&&<button disabled={busy} onClick={()=>act(`pause:${s.id}`,'Paused',()=>integrationApi.setStatus(s.id,'pause'))}>Pause</button>}{status==='disconnected'&&integration&&Boolean(schema[integration.slug])&&<button onClick={()=>setSelected(integration)}>Reconnect</button>}{status!=='disconnected'&&<button disabled={busy} onClick={()=>act(`disconnect:${s.id}`,'Disconnected',()=>integrationApi.setStatus(s.id,'disconnect'))}>Disconnect</button>}<button className="danger" disabled={busy} onClick={()=>window.confirm(`Delete ${s.label}?`)&&act(`delete:${s.id}`,'Deleted',()=>integrationApi.remove(s.id))}>Delete</button></div>};
 const visible=d.integrations.filter(x=>(category==='all'||x.category===category)&&`${x.name} ${x.slug}`.toLowerCase().includes(query.toLowerCase()));const clientSources=d.sources.filter(x=>!activeClient||x.client_id===activeClient);
 return <div className="ids-page"><nav className="ids-tabs">{tabs.map(([id,label,to])=><Link key={id} to={to as never} className={view===id?'active':''}>{label}</Link>)}</nav>{notice&&<div className="ids-note">{notice}</div>}{q.error&&<div className="ids-error">{String(q.error)}</div>}
 {view==='catalog'&&<><Head title="Integration Catalog" text="90 branded connectors with real lifecycle and connection actions."/><div className="ids-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search connector"/>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c==='all'?'All':connectorCategories[c]}</button>)}</div><section className="ids-grid">{visible.map(i=>{const s=clientSources.find(x=>x.integration_id===i.id);return <article className="connector-card" style={integrationBrandStyle(i.slug,i.category)} key={i.id}><div className="connector-top"><IntegrationBrandMark slug={i.slug} name={i.name} category={i.category}/><Pill value={i.lifecycle}/></div><div><h3>{i.name}</h3><p>{connectorCategories[i.category]} · {i.authType}</p></div><button className="connector-button" disabled={!s&&(d.mode!=='live'||!activeClient||!schema[i.slug])} onClick={()=>s?window.location.assign(activeClient?`/client/${activeClient}/data`:'/data/connections'):setSelected(i)}>{s?'Manage':schema[i.slug]?'Connect':'Adapter pending'}</button></article>})}</section></>}
 {view==='connections'&&<><Head title="Connection Manager" text="Connect, sync, pause, resume, reconnect, disconnect and delete sources." action={<Link className="ids-primary" to="/data">+ Add</Link>}/><Table heads={['Integration / source','Client','Status','Last sync','External ID','Actions']} rows={d.sources.map(s=>[<><b>{byIntegration.get(s.integration_id)?.name}</b><small>{s.label}</small></>,clients.get(s.client_id)||s.client_id,<Pill value={sourceStatus(s)}/>,date(s.last_sync_at),<code>{s.external_identifier}</code>,actions(s)])}/></>}
 {view==='agency'&&<><Head title="Agency Connections" text="Shared credentials, attachments, expiration and revocation."/><Table heads={['Connection','Account','Status','Attachments','Expires','Action']} rows={d.accounts.map(a=>[<><b>{byIntegration.get(a.integration_id)?.name}</b><small>{a.label}</small></>,<code>{a.external_account_id||'—'}</code>,<Pill value={a.status}/>,d.sources.filter(s=>s.account_id===a.id).length,date(a.expires_at),<button className="danger" disabled={a.status==='disconnected'} onClick={()=>window.confirm(`Revoke ${a.label}?`)&&act(`revoke:${a.id}`,'Revoked',()=>integrationApi.revokeAccount(a.id))}>Revoke</button>])}/></>}
 {view==='client'&&<><Head title="Data Source Management" text={`Client: ${activeClient?clients.get(activeClient)||activeClient:'not selected'}`} action={<Link className="ids-primary" to="/data">+ Add source</Link>}/><section className="ids-source-grid">{clientSources.map(s=>{const job=d.jobs.find(j=>j.data_source_id===s.id),run=d.runs.find(r=>r.data_source_id===s.id);return <article className="ids-source" key={s.id}><header><h3>{s.label}</h3><Pill value={sourceStatus(s)}/></header><p>{byIntegration.get(s.integration_id)?.name} · {s.external_identifier}</p><dl><dt>Last sync</dt><dd>{date(s.last_sync_at)}</dd><dt>Latest job</dt><dd>{job?`${job.state} ${job.period_from}→${job.period_to}`:'—'}</dd><dt>Latest run</dt><dd>{run?`${run.rows_written} rows`:'—'}</dd><dt>Error</dt><dd>{err(s.sync_error)}</dd></dl>{actions(s)}</article>})}</section></>}
 {view==='schema'&&<><Head title="Integration Schema" text="Entities, dimensions and metrics for implemented provider adapters."/><section className="ids-schema">{d.integrations.map(i=><article key={i.id}><IntegrationBrandMark slug={i.slug} name={i.name} category={i.category}/><h3>{i.name}</h3>{schema[i.slug]?<p>{schema[i.slug].join(' · ')}</p>:<p>Adapter schema pending · lifecycle={i.lifecycle}</p>}</article>)}</section></>}
 {view==='health'&&<><Head title="Sync Health" text="Queue, retries, freshness, errors and run history." action={<button className="ids-primary" onClick={()=>void refresh()}>Refresh</button>}/><div className="ids-stats"><b>Queued {d.jobs.filter(x=>x.state==='queued').length}</b><b>Running {d.jobs.filter(x=>x.state==='running').length}</b><b>Failed {d.jobs.filter(x=>x.state==='failed').length}</b><b>Stale sources {d.sources.filter(x=>!x.last_sync_at||Date.now()-new Date(x.last_sync_at).getTime()>172800000).length}</b></div><h3>Sync queue</h3><Table heads={['Source','Period','State','Attempts','Run after','Error']} rows={d.jobs.map(j=>{const s=bySource.get(j.data_source_id);return[<><b>{byIntegration.get(s?.integration_id||'')?.name}</b><small>{s?.label}</small></>,`${j.period_from}→${j.period_to}`,<Pill value={j.state}/>,`${j.attempts}/${j.max_attempts}`,date(j.run_after),err(j.last_error)]})}/><h3>Run history</h3><Table heads={['Source','State','Started','Finished','Fetched','Written','Error']} rows={d.runs.map(r=>{const s=bySource.get(r.data_source_id);return[<><b>{byIntegration.get(s?.integration_id||'')?.name}</b><small>{s?.label}</small></>,<Pill value={r.state}/>,date(r.started_at),date(r.finished_at),r.rows_fetched,r.rows_written,err(r.error)]})}/></>}
 {selected&&<ConnectDataSourceModal integration={selected} onClose={()=>setSelected(null)} onConnected={refresh}/>}</div>;
}
function Table({heads,rows}:{heads:string[];rows:ReactNode[][]}){return <div className="ids-table-wrap"><table className="ids-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="ids-empty">No data yet.</div>}</div>}
export const IntegrationCatalogPage=()=> <IntegrationsWorkspacePage view="catalog"/>;
export const ConnectionManagerPage=()=> <IntegrationsWorkspacePage view="connections"/>;
export const AgencyConnectionsPage=()=> <IntegrationsWorkspacePage view="agency"/>;
export const ClientDataSourcesPage=()=> <IntegrationsWorkspacePage view="client"/>;
export const IntegrationSchemaPage=()=> <IntegrationsWorkspacePage view="schema"/>;
export const SyncHealthPage=()=> <IntegrationsWorkspacePage view="health"/>;
