// @ts-nocheck
import React,{useMemo,useState}from'react';
import{useQuery}from'@tanstack/react-query';
import{Area,Bar,CartesianGrid,ComposedChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{ArrowUpDown,ChevronDown,ChevronRight,Download,RefreshCw,Search,TrendingDown,TrendingUp}from'lucide-react';
import{getSupabaseBrowserClient,hasSupabaseEnvironment}from'@imds/auth';
import{useI18n}from'../../i18n/I18nProvider';

const META_CAMPAIGNS=[
{id:'m1',name:'grizhaquiz1/11.06.2026/ALA',account:'Amanat Med Halyk',base:1.25,status:'PAUSED',adsets:['Wide/DC1']},
{id:'m2',name:'sustavi2/11.06.2026/ALA',account:'Amanat Med Halyk',base:.72,status:'PAUSED',adsets:['Wide/DC4']},
{id:'m3',name:'WA/Form_Test/02.06.2026',account:'Amanat Med Halyk',base:.8,status:'ACTIVE',adsets:['1group','2group']},
{id:'m4',name:'g_strat1_1806wa_grup1',account:'#570/BI toibekov (3)',base:1.1,status:'ACTIVE',adsets:['g_strat1_1806wa_grup1']},
{id:'m5',name:'n_strat1_0207wa_grup_3_remaster',account:'#570/BI toibekov (3)',base:.96,status:'ACTIVE',adsets:['n_strat1_0207wa_grup_3']},
];
const TIKTOK_CAMPAIGNS=[
{id:'t1',name:'Hernia | Free MRI review',account:'AMANAT MED Almaty',base:1.35,status:'ACTIVE',adsets:['Lumbar MRI 30–55','Broad audience']},
{id:'t2',name:'Lower back and leg pain',account:'AMANAT MED Almaty',base:1.15,status:'ACTIVE',adsets:['Sciatica interests','Blog retargeting']},
{id:'t3',name:'Neck and arm pain',account:'AMANAT MED Almaty',base:.75,status:'LEARNING',adsets:['Office workers','Lookalike 3%']},
{id:'t4',name:'Knee pain',account:'AMANAT MED Almaty',base:.65,status:'PAUSED',adsets:['Arthrosis 45+']},
];
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function demoRows(platform){const random=rng(platform==='Meta'?20260804:20260805),campaigns=platform==='Meta'?META_CAMPAIGNS:TIKTOK_CAMPAIGNS,rows=[];for(const[cIndex,c]of campaigns.entries())for(let offset=89;offset>=0;offset--){const date=new Date('2026-08-04');date.setDate(date.getDate()-offset);const spend=Math.round(c.base*(platform==='Meta'?52:42000)*(.72+random()*.56)*(c.status==='PAUSED'&&offset<7?.05:1)*100)/100,cpm=platform==='Meta'?4+random()*5:900+random()*500,impressions=Math.max(0,Math.round(spend/cpm*1000)),clicks=Math.round(impressions*(.009+random()*.018+(cIndex===3?.004:0))),leads=Math.round(clicks*(.035+random()*.09)),arrived=Math.round(leads*(.35+random()*.25)),sales=Math.round(arrived*(.4+random()*.25)),revenue=platform==='TikTok'?Math.round(sales*(68000+random()*35000)):0;rows.push({platform,report_date:date.toISOString().slice(0,10),account_name:c.account,campaign_id:c.id,campaign_name:c.name,effective_status:c.status,impressions,clicks,spend,leads,arrived,sales,revenue,adsets:c.adsets})}return rows}
const safe=(a,b)=>b>0?a/b:0;
function derive(t){return{...t,ctr:safe(t.clicks,t.impressions),cpc:safe(t.spend,t.clicks),cpl:safe(t.spend,t.leads),roas:safe(t.revenue,t.spend)}}
function aggregate(rows){return derive(rows.reduce((a,r)=>{for(const key of['impressions','clicks','spend','leads','arrived','sales','revenue'])a[key]+=Number(r[key]||0);return a},{impressions:0,clicks:0,spend:0,leads:0,arrived:0,sales:0,revenue:0}))}
function groupCampaigns(rows,unnamed){const groups={};for(const r of rows){const key=r.campaign_id||r.campaign_name;groups[key]??={campaign_id:key,campaign_name:r.campaign_name||unnamed,account_name:r.account_name||'',status:(r.effective_status||'ACTIVE').includes('PAUSED')?'PAUSED':r.effective_status==='LEARNING'?'LEARNING':'ACTIVE',adsets:r.adsets||[r.adset_name].filter(Boolean),impressions:0,clicks:0,spend:0,leads:0,arrived:0,sales:0,revenue:0};for(const metric of['impressions','clicks','spend','leads','arrived','sales','revenue'])groups[key][metric]+=Number(r[metric]||0)}return Object.values(groups).map(derive)}
function trend(rows){const days={};for(const r of rows){days[r.report_date]??={report_date:r.report_date,spend:0,leads:0};days[r.report_date].spend+=Number(r.spend||0);days[r.report_date].leads+=Number(r.leads||0)}return Object.values(days).sort((a,b)=>a.report_date.localeCompare(b.report_date))}
async function loadRows(platform){const fallback=demoRows(platform);if(!hasSupabaseEnvironment())return{rows:fallback,mode:platform==='Meta'?'importedPreview':'demo',warning:null};try{const client=getSupabaseBrowserClient(),start=new Date();start.setDate(start.getDate()-365);const{data,error}=await client.from('marketing_ads').select('report_date,account_name,campaign_id,campaign_name,effective_status,impressions,clicks,spend,leads,arrived,sales,revenue,adset_name').ilike('platform',`${platform}%`).gte('report_date',start.toISOString().slice(0,10)).order('report_date',{ascending:true});if(error)throw error;if(!data?.length)return{rows:fallback,mode:platform==='Meta'?'importedPreview':'demo',warning:'empty'};return{rows:data.map(row=>({...row,adsets:[row.adset_name].filter(Boolean)})),mode:'live',warning:null}}catch{return{rows:fallback,mode:platform==='Meta'?'importedPreview':'demo',warning:'unavailable'}}}
function Delta({current,previous,invert=false}){if(!previous)return <span className="paid-delta neutral">—</span>;const value=(current-previous)/previous*100,positive=invert?value<=0:value>=0;return <span className={`paid-delta ${positive?'positive':'negative'}`}>{value>=0?<TrendingUp size={12}/>:<TrendingDown size={12}/>} {Math.abs(value).toFixed(1)}%</span>}
function Kpi({label,value,current,previous,invert=false,sub}){return <div className="paid-kpi"><span>{label}</span><strong>{value}</strong><div><Delta current={current} previous={previous} invert={invert}/>{sub&&<small>{sub}</small>}</div></div>}
function SortHead({label,name,sort,onSort}){return <th onClick={()=>onSort(name)}><span>{label}<ArrowUpDown size={11} opacity={sort.key===name?1:.35}/></span></th>}

export function PaidAdsCampaignsPage({platform}:{platform:'Meta'|'TikTok'}){const{t,locale}=useI18n();const accent=platform==='Meta'?'#1877F2':'#25F4EE',secondary=platform==='Meta'?'#E1306C':'#FE2C55',[range,setRange]=useState(14),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState({key:'spend',dir:'desc'}),[expanded,setExpanded]=useState(new Set());const fmtNum=v=>Math.round(v).toLocaleString(locale),fmtMoney=v=>`${Math.round(v).toLocaleString(locale)} ₸`,fmtPct=v=>`${(v*100).toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2})}%`,fmtX=v=>`${v.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2})}×`;const query=useQuery({queryKey:['paid-ads',platform],queryFn:()=>loadRows(platform),staleTime:300000});const source=query.data||{rows:demoRows(platform),mode:'demo',warning:null},dates=[...new Set(source.rows.map(r=>r.report_date))].sort(),currentDates=new Set(dates.slice(-range)),previousDates=new Set(dates.slice(-range*2,-range)),currentRows=source.rows.filter(r=>currentDates.has(r.report_date)),previousRows=source.rows.filter(r=>previousDates.has(r.report_date)),totals=aggregate(currentRows),previous=aggregate(previousRows),chart=trend(currentRows);const campaigns=useMemo(()=>{let rows=groupCampaigns(currentRows,t('paid.unnamedCampaign'));if(search.trim())rows=rows.filter(r=>`${r.campaign_name} ${r.account_name}`.toLowerCase().includes(search.toLowerCase()));if(status!=='all')rows=rows.filter(r=>r.status===status);rows.sort((a,b)=>{const av=a[sort.key],bv=b[sort.key],result=typeof av==='string'?av.localeCompare(bv):av-bv;return sort.dir==='asc'?result:-result});return rows},[currentRows,search,status,sort,t]);const onSort=key=>setSort(value=>({key,dir:value.key===key&&value.dir==='desc'?'asc':'desc'})),toggle=id=>setExpanded(value=>{const next=new Set(value);next.has(id)?next.delete(id):next.add(id);return next}),exportCsv=()=>{const header=['campaign','account','status','spend','impressions','clicks','ctr','cpc','leads','cpl','sales','roas'].map(key=>t(`paid.table.${key}`)),lines=campaigns.map(r=>[r.campaign_name,r.account_name,t(`paid.statuses.${r.status.toLowerCase()}`),r.spend,r.impressions,r.clicks,(r.ctr*100).toFixed(2),r.cpc,r.leads,r.cpl,r.sales,r.roas].join(';')),blob=new Blob(['﻿'+[header.join(';'),...lines].join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${platform.toLowerCase()}-campaigns.csv`;a.click();URL.revokeObjectURL(url)};const funnel=[['impressions',totals.impressions],['clicks',totals.clicks],['leads',totals.leads],['arrived',totals.arrived],['sales',totals.sales]],funnelMax=funnel[0][1]||1;return <div className="paid-ads" style={{'--paid-accent':accent,'--paid-secondary':secondary} as React.CSSProperties}>
<style>{`.paid-ads{background:#0b0d12;color:#f5f7fb;border-radius:14px;padding:22px}.paid-head,.paid-controls,.paid-toolbar,.paid-kpi>div,.paid-things{display:flex;align-items:center}.paid-head{justify-content:space-between;gap:16px;margin-bottom:16px}.paid-head h2{margin:0 0 5px;font-size:21px}.paid-sub{color:#9298a6;font-size:12px}.paid-source{display:inline-flex;padding:3px 8px;border:1px solid #2a2f3a;border-radius:99px;margin-right:7px;color:var(--paid-accent)}.paid-controls{gap:7px;flex-wrap:wrap}.paid-controls button,.paid-search,.paid-select{border:1px solid #2a2f3a;background:#171a21;color:#f5f7fb;border-radius:9px;padding:7px 10px}.paid-controls button.active{color:var(--paid-accent)}.paid-warning{background:#2a2113;border:1px solid #5d431c;color:#f5c36a;padding:9px 11px;border-radius:9px;margin-bottom:12px}.paid-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:9px;margin-bottom:14px}.paid-kpi,.paid-panel{background:#15181f;border:1px solid #292e38;border-radius:11px}.paid-kpi{padding:13px}.paid-kpi>span{font-size:10px;color:#9298a6;text-transform:uppercase}.paid-kpi strong{display:block;font-size:19px;margin:8px 0}.paid-kpi>div{gap:6px}.paid-kpi small{color:#9298a6}.paid-delta{display:inline-flex;align-items:center;font-size:10px;font-weight:700}.paid-delta.positive{color:#38d996}.paid-delta.negative{color:#ff647c}.paid-panel{padding:16px;margin-bottom:14px}.paid-panel h3{font-size:13px;margin:0 0 12px}.paid-funnel{display:flex;flex-direction:column;gap:8px}.paid-funnel-row{display:grid;grid-template-columns:110px 1fr 90px;gap:10px;align-items:center}.paid-track{height:8px;background:#232731;border-radius:8px;overflow:hidden}.paid-fill{height:100%;background:linear-gradient(90deg,var(--paid-accent),var(--paid-secondary))}.paid-toolbar{justify-content:space-between;gap:10px}.paid-things{gap:8px}.paid-search{display:flex;align-items:center;gap:6px}.paid-search input{border:0;outline:0;background:transparent;color:#fff}.paid-table-wrap{overflow:auto}.paid-ads table{width:100%;border-collapse:collapse;font-size:12px}.paid-ads th,.paid-ads td{padding:10px 9px;border-bottom:1px solid #272c35;white-space:nowrap;text-align:right}.paid-ads th:first-child,.paid-ads td:first-child{text-align:left}.paid-campaign{display:flex;align-items:center;gap:7px}.paid-campaign button{border:0;background:transparent;color:#9298a6}.paid-campaign small{display:block;color:#9298a6}.paid-badge{padding:3px 7px;border-radius:99px;background:#222733}.paid-badge.ACTIVE{color:#38d996}.paid-badge.LEARNING{color:#f5c36a}.paid-total td{font-weight:800;background:#1b1f27}.paid-foot{font-size:11px;color:#9298a6;margin-top:10px}@media(max-width:1200px){.paid-kpis{grid-template-columns:repeat(3,1fr)}}`}</style>
<div className="paid-head"><div><h2>{t('paid.title',{platform})}</h2><div className="paid-sub"><span className="paid-source">{t(`paid.source.${source.mode}`)}</span>{dates.at(-range)||'—'} → {dates.at(-1)||'—'}</div></div><div className="paid-controls">{[7,14,30,90].map(day=><button key={day} className={range===day?'active':''} onClick={()=>setRange(day)}>{t('paid.days',{count:day})}</button>)}<button onClick={()=>void query.refetch()}><RefreshCw size={13}/> {t('paid.refresh')}</button><button onClick={exportCsv}><Download size={13}/> CSV</button></div></div>
{source.warning&&<div className="paid-warning">{t('paid.liveWarning',{reason:t(source.warning==='empty'?'paid.errors.emptyLiveData':'paid.errors.unavailable')})}</div>}
<div className="paid-kpis"><Kpi label={t('paid.metrics.spend')} value={fmtMoney(totals.spend)} current={totals.spend} previous={previous.spend}/><Kpi label={t('paid.metrics.impressions')} value={fmtNum(totals.impressions)} current={totals.impressions} previous={previous.impressions}/><Kpi label="CTR" value={fmtPct(totals.ctr)} current={totals.ctr} previous={previous.ctr}/><Kpi label="CPC" value={fmtMoney(totals.cpc)} current={totals.cpc} previous={previous.cpc} invert/><Kpi label={t('paid.metrics.leads')} value={fmtNum(totals.leads)} current={totals.leads} previous={previous.leads} sub={`CPL ${fmtMoney(totals.cpl)}`}/><Kpi label="ROAS" value={fmtX(totals.roas)} current={totals.roas} previous={previous.roas} sub={t('paid.salesCount',{count:totals.sales})}/></div>
<div className="paid-panel"><h3>{t('paid.chartTitle')}</h3><ResponsiveContainer width="100%" height={220}><ComposedChart data={chart}><CartesianGrid stroke="#242933" vertical={false}/><XAxis dataKey="report_date" tick={{fill:'#9298a6',fontSize:10}} tickFormatter={value=>value.slice(5)}/><YAxis yAxisId="spend" tick={{fill:'#9298a6',fontSize:10}}/><YAxis yAxisId="leads" orientation="right" tick={{fill:'#9298a6',fontSize:10}}/><Tooltip contentStyle={{background:'#1b1f27',border:'1px solid #2a2f3a'}}/><Area yAxisId="spend" type="monotone" dataKey="spend" stroke={accent} fill={accent} fillOpacity={.12}/><Bar yAxisId="leads" dataKey="leads" fill={secondary}/></ComposedChart></ResponsiveContainer></div>
<div className="paid-panel"><h3>{t('paid.funnelTitle')}</h3><div className="paid-funnel">{funnel.map(([key,value])=><div className="paid-funnel-row" key={key}><span>{t(`paid.funnel.${key}`)}</span><div className="paid-track"><div className="paid-fill" style={{width:`${Math.max(2,value/funnelMax*100)}%`}}/></div><strong>{fmtNum(value)}</strong></div>)}</div></div>
<div className="paid-panel"><div className="paid-toolbar"><h3>{t('paid.campaignsTitle',{count:campaigns.length})}</h3><div className="paid-things"><label className="paid-search"><Search size={13}/><input placeholder={t('paid.searchCampaign')} value={search} onChange={event=>setSearch(event.target.value)}/></label><select className="paid-select" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">{t('paid.statuses.all')}</option><option value="ACTIVE">{t('paid.statuses.active')}</option><option value="LEARNING">{t('paid.statuses.learning')}</option><option value="PAUSED">{t('paid.statuses.paused')}</option></select></div></div><div className="paid-table-wrap"><table><thead><tr>{['campaign','spend','impressions','clicks','ctr','cpc','leads','cpl','sales','roas'].map(key=><SortHead key={key} label={t(`paid.table.${key}`)} name={key==='campaign'?'campaign_name':key} sort={sort} onSort={onSort}/>)}</tr></thead><tbody>{campaigns.map(row=><React.Fragment key={row.campaign_id}><tr><td><div className="paid-campaign"><button onClick={()=>toggle(row.campaign_id)}>{expanded.has(row.campaign_id)?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button><div><strong>{row.campaign_name}</strong><small>{row.account_name}</small></div><span className={`paid-badge ${row.status}`}>{t(`paid.statuses.${row.status.toLowerCase()}`)}</span></div></td><td>{fmtMoney(row.spend)}</td><td>{fmtNum(row.impressions)}</td><td>{fmtNum(row.clicks)}</td><td>{fmtPct(row.ctr)}</td><td>{fmtMoney(row.cpc)}</td><td>{fmtNum(row.leads)}</td><td>{row.leads?fmtMoney(row.cpl):'—'}</td><td>{fmtNum(row.sales)}</td><td>{fmtX(row.roas)}</td></tr>{expanded.has(row.campaign_id)&&(row.adsets||[]).map(name=><tr key={`${row.campaign_id}-${name}`}><td>↳ {name}</td><td colSpan={9}/></tr>)}</React.Fragment>)}{!campaigns.length&&<tr><td colSpan={10}>{t('paid.empty')}</td></tr>}<tr className="paid-total"><td>{t('paid.total')}</td><td>{fmtMoney(totals.spend)}</td><td>{fmtNum(totals.impressions)}</td><td>{fmtNum(totals.clicks)}</td><td>{fmtPct(totals.ctr)}</td><td>{fmtMoney(totals.cpc)}</td><td>{fmtNum(totals.leads)}</td><td>{totals.leads?fmtMoney(totals.cpl):'—'}</td><td>{fmtNum(totals.sales)}</td><td>{fmtX(totals.roas)}</td></tr></tbody></table></div><div className="paid-foot">{t('paid.foot')}</div></div>
</div>}
export function MetaAdsCampaignsPage(){return <PaidAdsCampaignsPage platform="Meta"/>}
export function TikTokAdsCampaignsPage(){return <PaidAdsCampaignsPage platform="TikTok"/>}
