import {useEffect,useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useParams} from '@tanstack/react-router';
import {Area,Bar,CartesianGrid,ComposedChart,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowDown,ArrowUp,Download,RefreshCw,Search} from 'lucide-react';
import {useAuth} from '../../app/AuthProvider';
import {advertisingApi,type AdvertisingCampaign,type AdvertisingPlatform,type AdvertisingSort,type AdvertisingSummary,type AdvertisingWorkspace,type AdvertisingWorkspaceParams} from '../../advertising-api';
import './paid-ads-analytics.css';

type View='campaigns'|'funnel';
const platformLabels:Record<AdvertisingPlatform,string>={all:'Все каналы','meta-ads':'Meta Ads','tiktok-ads':'TikTok Ads','google-ads':'Google Ads'};
const ranges=[7,14,30,90,180];
function period(days:number){const to=new Date(),from=new Date();from.setUTCDate(to.getUTCDate()-days+1);return{dateFrom:from.toISOString().slice(0,10),dateTo:to.toISOString().slice(0,10)}}
const number=(value:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(value);
const percent=(value:number)=>new Intl.NumberFormat('ru-RU',{style:'percent',maximumFractionDigits:2}).format(value);
function currency(value:number,code:string){try{return new Intl.NumberFormat('ru-RU',{style:'currency',currency:code,maximumFractionDigits:0}).format(value)}catch{return`${number(value)} ${code}`}}
function Delta({current,previous,invert=false}:{current:number;previous:number;invert?:boolean}){if(!previous)return <span className="aa-delta neutral">—</span>;const change=(current-previous)/Math.abs(previous),good=invert?change<=0:change>=0;return <span className={`aa-delta ${good?'good':'bad'}`}>{change>=0?<ArrowUp size={12}/>:<ArrowDown size={12}/>} {percent(Math.abs(change))}</span>}
function Kpi({label,value,current,previous,invert}:{label:string;value:string;current:number;previous:number;invert?:boolean}){return <article className="aa-kpi"><span>{label}</span><strong>{value}</strong><Delta current={current} previous={previous} invert={invert}/></article>}
function platformPath(clientId:string,platform:AdvertisingPlatform){return platform==='all'?`/client/${clientId}/ads/campaigns`:`/client/${clientId}/${platform}/campaigns`}
function csvCell(value:unknown){const text=String(value??'');return /[;"\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}

function AdvertisingAnalyticsPage({view,lockedPlatform}:{view:View;lockedPlatform?:Exclude<AdvertisingPlatform,'all'>}){
  const{clientId}=useParams({strict:false}) as {clientId?:string};
  const{workspace}=useAuth();
  const agencyId=workspace?.activeAgency?.id;
  const[days,setDays]=useState(30),[selectedPlatform,setSelectedPlatform]=useState<AdvertisingPlatform>('all'),[accountId,setAccountId]=useState(''),[status,setStatus]=useState(''),[currencyCode,setCurrencyCode]=useState(''),[search,setSearch]=useState(''),[sortBy,setSortBy]=useState<AdvertisingSort>('spend'),[sortDir,setSortDir]=useState<'asc'|'desc'>('desc'),[page,setPage]=useState(1),[exporting,setExporting]=useState(false);
  const platform=lockedPlatform??selectedPlatform;
  const dates=useMemo(()=>period(days),[days]);
  const params=useMemo<AdvertisingWorkspaceParams>(()=>({agencyId:agencyId||'',clientId:clientId||'',...dates,platform,accountId:accountId||undefined,status:status||undefined,currency:currencyCode||undefined,search:search||undefined,sortBy,sortDir,page,pageSize:25}),[agencyId,clientId,dates,platform,accountId,status,currencyCode,search,sortBy,sortDir,page]);
  const query=useQuery({queryKey:['advertising-workspace',params],queryFn:()=>advertisingApi.workspace(params),enabled:Boolean(agencyId&&clientId),staleTime:60000});
  const data=query.data;
  useEffect(()=>{if(!currencyCode&&data?.effectiveCurrency)setCurrencyCode(data.effectiveCurrency)},[currencyCode,data?.effectiveCurrency]);
  const accounts=useMemo(()=>data?.filters.accounts.filter(item=>platform==='all'||item.platform===platform)??[],[data?.filters.accounts,platform]);
  useEffect(()=>{if(accountId&&!accounts.some(item=>item.id===accountId))setAccountId('')},[accountId,accounts]);
  function reset(next:()=>void){next();setPage(1)}
  function sort(key:AdvertisingSort){setPage(1);if(sortBy===key)setSortDir(value=>value==='desc'?'asc':'desc');else{setSortBy(key);setSortDir(['campaignName','accountName','status'].includes(key)?'asc':'desc')}}
  async function exportCsv(){if(!data||!agencyId||!clientId)return;setExporting(true);try{const rows:AdvertisingCampaign[]=[];for(let nextPage=1;nextPage<=data.campaigns.pages;nextPage+=1){const response=await advertisingApi.workspace({...params,page:nextPage,pageSize:100});rows.push(...response.campaigns.items)}const header=['Платформа','Аккаунт','Кампания','Статус','Валюта','Показы','Клики','CTR','Расход','CPC','Лиды','CPL','Целевые лиды','Визиты','Продажи','CPA','Выручка','ROAS'];const lines=rows.map(item=>[platformLabels[item.platform],item.accountName,item.campaignName,item.status,item.currency,item.impressions,item.clicks,item.ctr,item.spend,item.cpc,item.leads,item.cpl,item.targetLeads,item.arrived,item.sales,item.cpa,item.revenue,item.roas].map(csvCell).join(';'));const blob=new Blob(['\ufeff'+[header.join(';'),...lines].join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`advertising-${dates.dateFrom}-${dates.dateTo}.csv`;anchor.click();URL.revokeObjectURL(url)}finally{setExporting(false)}}
  if(!agencyId||!clientId)return <div className="aa-state">Выберите агентство и клиента.</div>;
  return <div className="aa-page">
    <header className="aa-header"><div><span className="aa-eyebrow">Advertising Analytics</span><h2>{view==='funnel'?'Воронка рекламы':'Кампании'}</h2><p>{dates.dateFrom} — {dates.dateTo} · сравнение с предыдущим периодом</p></div><div className="aa-header-actions"><button onClick={()=>void query.refetch()}><RefreshCw size={15}/>Обновить</button><button onClick={()=>void exportCsv()} disabled={!data||exporting}><Download size={15}/>{exporting?'Экспорт…':'CSV'}</button></div></header>
    <nav className="aa-tabs"><a className={view==='campaigns'&&!lockedPlatform?'active':''} href={platformPath(clientId,'all')}>Все каналы</a>{(['meta-ads','tiktok-ads','google-ads'] as const).map(item=><a key={item} className={lockedPlatform===item?'active':''} href={platformPath(clientId,item)}>{platformLabels[item]}</a>)}<a className={view==='funnel'?'active':''} href={`/client/${clientId}/ads/funnel`}>Воронка</a></nav>
    <section className="aa-filters"><div className="aa-range">{ranges.map(value=><button key={value} className={days===value?'active':''} onClick={()=>reset(()=>setDays(value))}>{value}д</button>)}</div>{!lockedPlatform&&<select value={selectedPlatform} onChange={event=>reset(()=>setSelectedPlatform(event.target.value as AdvertisingPlatform))}>{Object.entries(platformLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>}<select value={accountId} onChange={event=>reset(()=>setAccountId(event.target.value))}><option value="">Все аккаунты</option>{accounts.map(item=><option key={`${item.platform}:${item.id}`} value={item.id}>{item.name}</option>)}</select><select value={status} onChange={event=>reset(()=>setStatus(event.target.value))}><option value="">Все статусы</option>{data?.filters.statuses.map(item=><option key={item} value={item}>{item}</option>)}</select><select value={currencyCode||data?.effectiveCurrency||'KZT'} onChange={event=>reset(()=>setCurrencyCode(event.target.value))}>{(data?.filters.currencies.length?data.filters.currencies:[data?.effectiveCurrency||'KZT']).map(item=><option key={item} value={item}>{item}</option>)}</select><label className="aa-search"><Search size={15}/><input value={search} onChange={event=>reset(()=>setSearch(event.target.value))} placeholder="Кампания или аккаунт"/></label></section>
    {data?.currencySelectionRequired&&<div className="aa-warning">В источниках несколько валют. Денежные показатели рассчитаны только в выбранной валюте {data.effectiveCurrency}.</div>}
    {query.isLoading&&<div className="aa-state">Загрузка рекламной аналитики…</div>}
    {query.error&&<div className="aa-state error"><strong>Не удалось загрузить данные</strong><span>{query.error instanceof Error?query.error.message:String(query.error)}</span><button onClick={()=>void query.refetch()}>Повторить</button></div>}
    {data&&<AnalyticsContent view={view} data={data} currencyCode={data.effectiveCurrency} sortBy={sortBy} sortDir={sortDir} onSort={sort} onPage={setPage}/>}  
  </div>;
}

function AnalyticsContent({view,data,currencyCode,sortBy,sortDir,onSort,onPage}:{view:View;data:AdvertisingWorkspace;currencyCode:string;sortBy:AdvertisingSort;sortDir:'asc'|'desc';onSort:(key:AdvertisingSort)=>void;onPage:(page:number)=>void}){
  const current=data.current,previous=data.previous;
  const kpis:Array<{key:string;label:string;value:string;current:number;previous:number;invert?:boolean}>=[
    {key:'spend',label:'Расход',value:currency(current.spend,currencyCode),current:current.spend,previous:previous.spend},
    {key:'impressions',label:'Показы',value:number(current.impressions),current:current.impressions,previous:previous.impressions},
    {key:'ctr',label:'CTR',value:percent(current.ctr),current:current.ctr,previous:previous.ctr},
    {key:'cpc',label:'CPC',value:currency(current.cpc,currencyCode),current:current.cpc,previous:previous.cpc,invert:true},
    {key:'leads',label:'Лиды',value:number(current.leads),current:current.leads,previous:previous.leads},
    {key:'cpl',label:'CPL',value:currency(current.cpl,currencyCode),current:current.cpl,previous:previous.cpl,invert:true},
    {key:'sales',label:'Продажи',value:number(current.sales),current:current.sales,previous:previous.sales},
    {key:'roas',label:'ROAS',value:`${current.roas.toFixed(2)}×`,current:current.roas,previous:previous.roas},
  ];
  return <><section className="aa-kpis">{kpis.map(item=><Kpi key={item.key} label={item.label} value={item.value} current={item.current} previous={item.previous} invert={item.invert}/>)}</section><section className="aa-panels"><article className="aa-panel aa-trend"><header><h3>Динамика</h3><span>Расход и лиды по дням</span></header><ResponsiveContainer width="100%" height={300}><ComposedChart data={data.trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis yAxisId="money" tick={{fontSize:11}}/><YAxis yAxisId="leads" orientation="right" tick={{fontSize:11}}/><Tooltip formatter={(value,name)=>String(name)==='spend'?currency(Number(value),currencyCode):number(Number(value))}/><Legend/><Area yAxisId="money" type="monotone" dataKey="spend" name="Расход" stroke="#2563eb" fill="#2563eb" fillOpacity={.12}/><Bar yAxisId="leads" dataKey="leads" name="Лиды" fill="#22c55e" radius={[4,4,0,0]}/></ComposedChart></ResponsiveContainer></article><FunnelCard data={data.funnel}/></section>{view==='campaigns'?<CampaignTable items={data.campaigns.items} currencyCode={currencyCode} sortBy={sortBy} sortDir={sortDir} onSort={onSort} page={data.campaigns.page} pages={data.campaigns.pages} total={data.campaigns.total} onPage={onPage}/>:<FunnelDetails current={current} currencyCode={currencyCode}/>}</>;
}

function FunnelCard({data}:{data:Array<{key:string;label:string;value:number;conversionFromPrevious:number}>}){const max=data[0]?.value||1;return <article className="aa-panel aa-funnel"><header><h3>Воронка</h3><span>Конверсия между этапами</span></header><div className="aa-funnel-list">{data.map((item,index)=><div className="aa-funnel-row" key={item.key}><div><strong>{item.label}</strong><span>{number(item.value)}</span></div><div className="aa-funnel-track"><span style={{width:`${Math.max(2,item.value/max*100)}%`}}/></div><small>{index===0?'100%':percent(item.conversionFromPrevious)}</small></div>)}</div></article>}
function FunnelDetails({current,currencyCode}:{current:AdvertisingSummary;currencyCode:string}){const rows:Array<[string,number]>=[['Клик → лид',current.clickToLead],['Лид → продажа',current.leadToSale],['Стоимость лида',current.cpl],['Стоимость продажи',current.cpa],['Выручка',current.revenue],['ROAS',current.roas]];return <section className="aa-panel"><header><h3>Эффективность воронки</h3><span>Ключевые переходы и экономика</span></header><div className="aa-funnel-details">{rows.map(([label,value],index)=><div key={label}><span>{label}</span><strong>{index<2?percent(value):index<5?currency(value,currencyCode):`${value.toFixed(2)}×`}</strong></div>)}</div></section>}
function CampaignTable({items,currencyCode,sortBy,sortDir,onSort,page,pages,total,onPage}:{items:AdvertisingCampaign[];currencyCode:string;sortBy:AdvertisingSort;sortDir:'asc'|'desc';onSort:(key:AdvertisingSort)=>void;page:number;pages:number;total:number;onPage:(page:number)=>void}){const columns:Array<[string,AdvertisingSort]>=[['Кампания','campaignName'],['Статус','status'],['Расход','spend'],['Показы','impressions'],['Клики','clicks'],['CTR','ctr'],['CPC','cpc'],['Лиды','leads'],['CPL','cpl'],['Целевые','targetLeads'],['Визиты','arrived'],['Продажи','sales'],['CPA','cpa'],['Выручка','revenue'],['ROAS','roas']];return <section className="aa-panel aa-table-panel"><header><div><h3>Кампании</h3><span>{total} кампаний</span></div></header><div className="aa-table-wrap"><table><thead><tr>{columns.map(([label,key])=><th key={key} className={key==='campaignName'?'left':''}><button onClick={()=>onSort(key)}>{label}{sortBy===key&&(sortDir==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button></th>)}</tr></thead><tbody>{items.map(item=><tr key={`${item.platform}:${item.accountId}:${item.campaignId}`}><td className="left"><strong>{item.campaignName}</strong><small>{platformLabels[item.platform]} · {item.accountName}</small></td><td><span className={`aa-status aa-status--${item.status.toLowerCase()}`}>{item.status}</span></td><td>{currency(item.spend,currencyCode)}</td><td>{number(item.impressions)}</td><td>{number(item.clicks)}</td><td>{percent(item.ctr)}</td><td>{currency(item.cpc,currencyCode)}</td><td>{number(item.leads)}</td><td>{currency(item.cpl,currencyCode)}</td><td>{number(item.targetLeads)}</td><td>{number(item.arrived)}</td><td>{number(item.sales)}</td><td>{currency(item.cpa,currencyCode)}</td><td>{currency(item.revenue,currencyCode)}</td><td>{item.roas.toFixed(2)}×</td></tr>)}</tbody></table>{!items.length&&<div className="aa-empty">По выбранным фильтрам кампаний нет.</div>}</div><footer className="aa-pagination"><span>Страница {page} из {pages}</span><div><button disabled={page<=1} onClick={()=>onPage(page-1)}>Назад</button><button disabled={page>=pages} onClick={()=>onPage(page+1)}>Далее</button></div></footer></section>}

export const AllAdsCampaignsPage=()=> <AdvertisingAnalyticsPage view="campaigns"/>;
export const MetaAdsCampaignsPage=()=> <AdvertisingAnalyticsPage view="campaigns" lockedPlatform="meta-ads"/>;
export const TikTokAdsCampaignsPage=()=> <AdvertisingAnalyticsPage view="campaigns" lockedPlatform="tiktok-ads"/>;
export const GoogleAdsCampaignsPage=()=> <AdvertisingAnalyticsPage view="campaigns" lockedPlatform="google-ads"/>;
export const FunnelAnalyticsPage=()=> <AdvertisingAnalyticsPage view="funnel"/>;
