import {useState} from 'react';
import {Button,Card} from '@imds/ui';
import {useAuth} from '../../app/AuthProvider';

export function AuthenticationPage(){
  const{session,workspace,loading,error,refreshSession,signOut}=useAuth();
  const[notice,setNotice]=useState('');
  const expiresAt=session?.expires_at?new Date(session.expires_at*1000):null;
  const identities=session?.user.identities??[];
  async function refresh(){setNotice('');await refreshSession();setNotice('Сессия успешно обновлена.');}
  async function logoutEverywhere(){setNotice('');await signOut('global');}
  return <div className="platform-core-page">
    <header className="platform-core-head"><div><span>Platform Core</span><h2>Authentication</h2><p>Управление текущей учётной записью, токенами и жизненным циклом сессии.</p></div><span className="core-state core-state--progress">В работе</span></header>
    {error&&<div className="form-error">{error}</div>}{notice&&<div className="form-notice">{notice}</div>}
    <section className="platform-core-grid">
      <Card className="core-panel"><h3>Текущая сессия</h3><dl><dt>Пользователь</dt><dd>{workspace?.currentUser.name||'—'}</dd><dt>Email</dt><dd>{workspace?.currentUser.email||session?.user.email||'—'}</dd><dt>User ID</dt><dd className="core-mono">{session?.user.id||'demo-user'}</dd><dt>Провайдер</dt><dd>{String(session?.user.app_metadata?.provider||'demo')}</dd><dt>Истекает</dt><dd>{expiresAt?expiresAt.toLocaleString('ru-RU'):'Демо-сессия'}</dd></dl></Card>
      <Card className="core-panel"><h3>Управление</h3><div className="core-actions"><Button disabled={loading||!session} onClick={()=>void refresh()}>{loading?'Обновление…':'Обновить сессию'}</Button><Button variant="secondary" disabled={loading||!session} onClick={()=>void logoutEverywhere()}>Выйти на всех устройствах</Button></div><p className="core-hint">Access token хранится в Supabase Auth, автоматически обновляется и не сохраняется в бизнес-таблицах.</p></Card>
      <Card className="core-panel core-panel--wide"><h3>Подключённые identities</h3><div className="core-identity-list">{identities.length?identities.map(identity=><div key={identity.id}><div><strong>{identity.provider}</strong><span>{String(identity.identity_data?.email??identity.id)}</span></div><b>Активна</b></div>):<div><div><strong>Demo identity</strong><span>Локальный режим</span></div><b>Demo</b></div>}</div></Card>
      <Card className="core-panel core-panel--wide"><h3>Поддерживаемые сценарии</h3><div className="core-checks"><span>✓ Email и пароль</span><span>✓ Magic Link</span><span>✓ Восстановление пароля</span><span>✓ Обновление пароля</span><span>✓ Автообновление токена</span><span>✓ Локальный и глобальный logout</span><span>✓ Auth state listener</span><span>✓ Session persistence</span><span>○ MFA/TOTP</span><span>○ Device history</span></div></Card>
    </section><style>{`.platform-core-page{display:flex;flex-direction:column;gap:16px}.platform-core-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;background:#fff;border:1px solid #dbe2ea;padding:22px}.platform-core-head>div>span{font-size:10px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:#667085}.platform-core-head h2{font-size:28px;margin:6px 0}.platform-core-head p{margin:0;color:#667085}.core-state{padding:7px 10px;font-size:10px;font-weight:800;text-transform:uppercase}.core-state--progress{background:#fff3cd;color:#8a5b00}.platform-core-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.core-panel{padding:20px}.core-panel--wide{grid-column:1/-1}.core-panel h3{margin:0 0 16px}.core-panel dl{margin:0;display:grid;grid-template-columns:130px 1fr;gap:10px}.core-panel dt{color:#667085}.core-panel dd{margin:0;font-weight:700;overflow-wrap:anywhere}.core-mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.core-actions{display:flex;gap:8px;flex-wrap:wrap}.core-hint{color:#667085;line-height:1.55}.core-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.core-checks span{padding:10px 12px;background:#f5f9ff;border:1px solid #dbe7f5;color:#235ea7;font-size:12px}.core-identity-list{display:flex;flex-direction:column;gap:8px}.core-identity-list>div{display:flex;justify-content:space-between;gap:16px;padding:11px 12px;background:#f8fafc;border:1px solid #e4e7ec}.core-identity-list span{display:block;color:#667085;font-size:11px;margin-top:3px}.core-identity-list b{color:#0064d2;font-size:11px}@media(max-width:900px){.platform-core-grid{grid-template-columns:1fr}.core-panel--wide{grid-column:auto}.core-checks{grid-template-columns:1fr}}`}</style>
  </div>;
}
