import {useEffect,useMemo,useState} from 'react';
import {Card} from '@imds/ui';
import {challengeAndVerifyTotp,enrollTotp,getAssuranceLevel,listAuthActivity,listAuthSessions,listMfaFactors,signOut,unenrollMfaFactor,verifyTotp,type AssuranceLevel,type AuthActivityRecord,type AuthSessionRecord,type MfaEnrollment,type MfaFactor} from '@imds/auth';
import {useAuth} from '../../app/AuthProvider';
import {PlatformCoreLayout,PlatformEmptyState,PlatformLoadingState,type PlatformCoreTab} from './PlatformCoreLayout';

const tabs:PlatformCoreTab[]=[
  {id:'overview',label:'Обзор',description:'Состояние защиты'},
  {id:'methods',label:'Способы входа',description:'Пароль и OAuth'},
  {id:'mfa',label:'MFA',description:'TOTP и AAL2'},
  {id:'sessions',label:'Сессии',description:'Устройства и выход'},
  {id:'activity',label:'Активность',description:'История Auth'},
];

export function AuthenticationPage(){
  const{session,workspace,loading,error,refreshSession}=useAuth();
  const[notice,setNotice]=useState('');
  const[localError,setLocalError]=useState('');
  const[sessions,setSessions]=useState<AuthSessionRecord[]>([]);
  const[activity,setActivity]=useState<AuthActivityRecord[]>([]);
  const[factors,setFactors]=useState<MfaFactor[]>([]);
  const[assurance,setAssurance]=useState<AssuranceLevel|null>(null);
  const[enrollment,setEnrollment]=useState<MfaEnrollment|null>(null);
  const[code,setCode]=useState('');
  const[busy,setBusy]=useState(false);
  const[activityQuery,setActivityQuery]=useState('');
  const verifiedFactor=useMemo(()=>factors.find(item=>item.status==='verified')??null,[factors]);
  const identities=session?.user.identities??[];
  const expiresAt=session?.expires_at?new Date(session.expires_at*1000):null;
  const emailConfirmedAt=session?.user.email_confirmed_at?new Date(session.user.email_confirmed_at):null;
  const filteredActivity=useMemo(()=>activity.filter(item=>`${item.action} ${item.provider??''} ${item.ipAddress??''}`.toLowerCase().includes(activityQuery.toLowerCase())),[activity,activityQuery]);

  async function loadSecurity(){if(!session)return;setBusy(true);setLocalError('');try{const[nextSessions,nextActivity,nextFactors,nextAssurance]=await Promise.all([listAuthSessions(),listAuthActivity(50),listMfaFactors(),getAssuranceLevel()]);setSessions(nextSessions);setActivity(nextActivity);setFactors(nextFactors);setAssurance(nextAssurance)}catch(value){setLocalError(value instanceof Error?value.message:'Не удалось загрузить данные безопасности.')}finally{setBusy(false)}}
  useEffect(()=>{void loadSecurity()},[session?.access_token]);
  async function refresh(){setNotice('');await refreshSession();await loadSecurity();setNotice('Сессия успешно обновлена.')}
  async function beginEnrollment(){setBusy(true);setLocalError('');try{setEnrollment(await enrollTotp());setCode('')}catch(value){setLocalError(value instanceof Error?value.message:'Не удалось создать TOTP-фактор.')}finally{setBusy(false)}}
  async function confirmEnrollment(){if(!enrollment||code.length!==6)return;setBusy(true);setLocalError('');try{await verifyTotp(enrollment.id,code);setEnrollment(null);setCode('');await refreshSession();await loadSecurity();setNotice('Двухфакторная аутентификация включена.')}catch(value){setLocalError(value instanceof Error?value.message:'Неверный код подтверждения.')}finally{setBusy(false)}}
  async function elevate(){if(!verifiedFactor||code.length!==6)return;setBusy(true);setLocalError('');try{await challengeAndVerifyTotp(verifiedFactor.id,code);setCode('');await refreshSession();await loadSecurity();setNotice('Сессия повышена до AAL2.')}catch(value){setLocalError(value instanceof Error?value.message:'Неверный код MFA.')}finally{setBusy(false)}}
  async function removeFactor(factorId:string){if(!window.confirm('Удалить MFA-фактор? После этого вход будет защищён только основным способом.'))return;setBusy(true);setLocalError('');try{await unenrollMfaFactor(factorId);await loadSecurity();setNotice('MFA-фактор удалён.')}catch(value){setLocalError(value instanceof Error?value.message:'Не удалось удалить MFA-фактор.')}finally{setBusy(false)}}
  async function logoutOthers(){if(!window.confirm('Завершить все другие активные сессии?'))return;await signOut('others');await loadSecurity();setNotice('Другие сессии завершены.')}
  const securityScore=[Boolean(emailConfirmedAt),Boolean(verifiedFactor),assurance?.currentLevel==='aal2',sessions.length<=2].filter(Boolean).length;

  return <PlatformCoreLayout title="Authentication" description="Учётная запись, способы входа, MFA, устройства, история входов и жизненный цикл сессий." tabs={tabs} defaultTab="overview" actions={<button className="pc-button pc-button--primary" disabled={loading||busy||!session} onClick={()=>void refresh()}>{busy?'Обновление…':'Обновить данные'}</button>} notice={<>{(error||localError)&&<div className="pc-banner pc-banner--error">{error||localError}</div>}{notice&&<div className="pc-banner pc-banner--success">{notice}</div>}</>}>
    {activeTab=>{
      if(busy&&!sessions.length&&activeTab!=='mfa')return <PlatformLoadingState label="Загрузка данных безопасности…"/>;
      if(activeTab==='overview')return <><section className="pc-grid pc-grid--stats"><Card className="pc-stat"><span>Уровень защиты</span><strong>{securityScore}/4</strong><small>{verifiedFactor?'MFA подключён':'MFA не подключён'}</small></Card><Card className="pc-stat"><span>Текущий AAL</span><strong>{assurance?.currentLevel??'aal1'}</strong><small>Следующий: {assurance?.nextLevel??'aal1'}</small></Card><Card className="pc-stat"><span>Активные сессии</span><strong>{sessions.length}</strong><small>{sessions.filter(item=>!item.isCurrent).length} других устройств</small></Card><Card className="pc-stat"><span>Email</span><strong>{emailConfirmedAt?'Подтверждён':'Не подтверждён'}</strong><small>{workspace?.currentUser.email||session?.user.email||'—'}</small></Card></section><section className="pc-grid"><Card className="pc-card"><h2>Текущая сессия</h2><dl className="pc-kv"><dt>Пользователь</dt><dd>{workspace?.currentUser.name||'—'}</dd><dt>User ID</dt><dd className="pc-mono">{session?.user.id||'demo-user'}</dd><dt>Создана</dt><dd>{session?.user.created_at?new Date(session.user.created_at).toLocaleString('ru-RU'):'—'}</dd><dt>Истекает</dt><dd>{expiresAt?expiresAt.toLocaleString('ru-RU'):'Демо-сессия'}</dd></dl></Card><Card className="pc-card"><h2>Рекомендации</h2><div className="pc-list"><div className="pc-list__row"><div><strong>Email verification</strong><span>Подтвердите основной адрес</span></div><span className={`pc-badge ${emailConfirmedAt?'pc-badge--on':'pc-badge--off'}`}>{emailConfirmedAt?'Готово':'Требуется'}</span></div><div className="pc-list__row"><div><strong>MFA / TOTP</strong><span>Защита вторым фактором</span></div><span className={`pc-badge ${verifiedFactor?'pc-badge--on':'pc-badge--off'}`}>{verifiedFactor?'Готово':'Требуется'}</span></div></div></Card></section></>;
      if(activeTab==='methods')return <section className="pc-grid"><Card className="pc-card pc-card--wide"><h2>Способы входа</h2><p>Подключённые identities определяются Supabase Auth. Основной email-метод всегда отображается отдельно.</p><div className="pc-list"><div className="pc-list__row"><div><strong>Email / password</strong><span>{workspace?.currentUser.email||session?.user.email||'Основной способ входа'}</span></div><span className="pc-badge pc-badge--on">Активен</span></div>{identities.map(identity=><div className="pc-list__row" key={identity.id}><div><strong>{identity.provider==='azure'?'Microsoft':identity.provider}</strong><span>{String(identity.identity_data?.email??identity.identity_data?.preferred_username??identity.id)}</span></div><span className="pc-badge pc-badge--on">Подключён</span></div>)}</div></Card></section>;
      if(activeTab==='mfa')return <section className="pc-grid"><Card className="pc-card pc-card--wide"><h2>MFA / TOTP</h2>{!verifiedFactor&&!enrollment&&<PlatformEmptyState title="Второй фактор не подключён" description="Подключите приложение-аутентификатор. QR-код можно отсканировать позже, когда будет доступно устройство." action={<button className="pc-button pc-button--primary" disabled={busy||!session} onClick={()=>void beginEnrollment()}>Начать подключение</button>}/>} {enrollment&&<div className="pc-mfa"><img src={enrollment.totp.qr_code} alt="QR-код TOTP"/><div className="pc-form"><div><strong>1. Отсканируйте QR-код</strong><p>Либо добавьте секрет вручную.</p><div className="pc-secret">{enrollment.totp.secret}</div></div><label>2. Введите код<input inputMode="numeric" maxLength={6} placeholder="123456" value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,''))}/></label><div className="pc-actions"><button className="pc-button" onClick={()=>{setEnrollment(null);setCode('')}}>Отмена</button><button className="pc-button pc-button--primary" disabled={busy||code.length!==6} onClick={()=>void confirmEnrollment()}>Подтвердить TOTP</button></div></div></div>} {verifiedFactor&&<div className="pc-grid"><Card className="pc-card"><h3>{verifiedFactor.friendly_name||'Authenticator'}</h3><p>Статус: {verifiedFactor.status}. Создан: {new Date(verifiedFactor.created_at).toLocaleString('ru-RU')}.</p><button className="pc-button pc-button--danger" disabled={busy} onClick={()=>void removeFactor(verifiedFactor.id)}>Удалить фактор</button></Card><Card className="pc-card"><h3>Повышение до AAL2</h3>{assurance?.currentLevel==='aal2'?<div className="pc-banner pc-banner--success">Текущая сессия уже подтверждена вторым фактором.</div>:<div className="pc-form"><label>Код MFA<input inputMode="numeric" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,''))}/></label><button className="pc-button pc-button--primary" disabled={busy||code.length!==6} onClick={()=>void elevate()}>Подтвердить AAL2</button></div>}</Card></div>}</Card></section>;
      if(activeTab==='sessions')return <section className="pc-grid"><Card className="pc-card pc-card--wide"><div className="pc-toolbar"><div><h2>Активные устройства и сессии</h2><p>Управляйте текущей и другими сессиями.</p></div><div className="pc-actions"><button className="pc-button" disabled={sessions.length<2} onClick={()=>void logoutOthers()}>Завершить другие</button><button className="pc-button pc-button--danger" disabled={!session} onClick={()=>{if(window.confirm('Выйти на всех устройствах?'))void signOut('global')}}>Выйти везде</button></div></div>{sessions.length?<div className="pc-list">{sessions.map(item=><div className="pc-list__row" key={item.id}><div><strong>{item.isCurrent?'Текущее устройство':'Другая сессия'}</strong><span>{item.userAgent||'Неизвестное устройство'}</span></div><span>{item.ipAddress||'IP скрыт'}</span><span>{item.aal}</span><span>{item.refreshedAt?new Date(item.refreshedAt).toLocaleString('ru-RU'):'—'}</span></div>)}</div>:<PlatformEmptyState title="Активные сессии не найдены" description="Список появится после первого входа через Supabase Auth."/>}</Card></section>;
      return <section className="pc-grid"><Card className="pc-card pc-card--wide"><div className="pc-toolbar"><div><h2>История входов и Auth-событий</h2><p>Последние события текущей учётной записи.</p></div><input aria-label="Поиск по истории" placeholder="Поиск по событию, provider или IP" value={activityQuery} onChange={event=>setActivityQuery(event.target.value)}/></div>{filteredActivity.length?<div className="pc-list">{filteredActivity.map(item=><div className="pc-list__row" key={item.id}><div><strong>{item.action}</strong><span>{item.provider||'auth'}</span></div><span>{item.ipAddress||'—'}</span><span>{item.userAgent||'—'}</span><span>{item.createdAt?new Date(item.createdAt).toLocaleString('ru-RU'):'—'}</span></div>)}</div>:<PlatformEmptyState title={activityQuery?'Ничего не найдено':'Событий пока нет'} description={activityQuery?'Измените поисковый запрос.':'События появятся после входов, восстановления пароля и изменений безопасности.'}/>}</Card></section>;
    }}
  </PlatformCoreLayout>;
}
