import type{Session}from'@supabase/supabase-js';
export type ClientStatus='active'|'paused'|'archived';export type ClientUserRole='owner'|'manager'|'editor'|'viewer';export type ClientUserStatus='invited'|'active'|'suspended';
export interface ClientRecord{id:string;agency_id:string;company:string;url:string|null;timezone:string;country:string|null;language:string;currency:string;start_date:string|null;logo_url:string|null;brand_color:string;status:ClientStatus;industry:string|null;group_id:string|null;group_name:string|null;account_manager_id:string|null;account_manager_name:string|null;contacts:Record<string,unknown>[];goals:string;notes:string;analytics_settings:Record<string,unknown>;attribution_settings:Record<string,unknown>;tracking_settings:Record<string,unknown>;retention_days:number;agency_markup:number;tags:string[];connected_sources_count:number;created_at:string;updated_at:string}
export interface ClientGroup{id:string;agency_id:string;name:string;description:string;color:string;client_count:number}export interface ClientUser{client_id:string;user_id:string;role:ClientUserRole;status:ClientUserStatus;permissions:string[];name:string|null;email:string|null;created_at:string}
export type ClientInput={agencyId:string;company:string;url?:string|null;timezone?:string;country?:string|null;language?:string;currency?:string;startDate?:string|null;logoUrl?:string|null;brandColor?:string;status?:ClientStatus;industry?:string|null;groupId?:string|null;accountManagerId?:string|null;contacts?:Record<string,unknown>[];goals?:string;notes?:string;analyticsSettings?:Record<string,unknown>;attributionSettings?:Record<string,unknown>;trackingSettings?:Record<string,unknown>;retentionDays?:number;agencyMarkup?:number;tags?:string[]};
const base=()=>import.meta.env.VITE_CLIENTS_API_URL?.replace(/\/$/,'');async function request<T>(path:string,session:Session|null,init?:RequestInit){if(!base()||!session)throw new Error('CLIENTS_API_NOT_CONFIGURED');const r=await fetch(`${base()}${path}`,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`,...init?.headers}});if(!r.ok)throw new Error(await r.text()||`CLIENTS_API_${r.status}`);return r.json()as Promise<T>}
export async function listClients(agencyId:string,session:Session|null,_mode:unknown,_fallback:unknown[],filters:{search?:string;status?:string;groupId?:string}={}){const p=new URLSearchParams({agencyId});Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));return(request<{items:ClientRecord[]}>(`/v1/clients?${p}`,session)).then(r=>r.items)}
export async function getClient(id:string,agencyId:string,session:Session|null,_mode:unknown,_fallback:unknown[]){return request<ClientRecord>(`/v1/clients/${id}?agencyId=${agencyId}`,session)}
export async function saveClient(id:string|null,input:ClientInput,session:Session|null,_mode:unknown){return request<ClientRecord>(id?`/v1/clients/${id}`:'/v1/clients',session,{method:id?'PATCH':'POST',body:JSON.stringify(input)})}
export async function archiveClient(id:string,agencyId:string,session:Session|null,_mode:unknown){await request(`/v1/clients/${id}?agencyId=${agencyId}`,session,{method:'DELETE'})}
export async function listGroups(agencyId:string,session:Session|null,_mode:unknown){return(request<{items:ClientGroup[]}>(`/v1/client-groups?agencyId=${agencyId}`,session)).then(r=>r.items)}
export async function createGroup(input:{agencyId:string;name:string;description:string;color:string},session:Session|null,_mode:unknown){return request<ClientGroup>('/v1/client-groups',session,{method:'POST',body:JSON.stringify(input)})}
export async function updateGroup(id:string,input:{agencyId:string;name?:string;description?:string;color?:string},session:Session|null,_mode:unknown){return request<ClientGroup>(`/v1/client-groups/${id}`,session,{method:'PATCH',body:JSON.stringify(input)})}
export async function deleteGroup(id:string,agencyId:string,session:Session|null,_mode:unknown){await request(`/v1/client-groups/${id}?agencyId=${agencyId}`,session,{method:'DELETE'})}
export async function listClientUsers(clientId:string,agencyId:string,session:Session|null,_mode:unknown){return(request<{items:ClientUser[]}>(`/v1/clients/${clientId}/users?agencyId=${agencyId}`,session)).then(r=>r.items)}
export async function inviteClientUser(clientId:string,input:{agencyId:string;email:string;role:ClientUserRole;permissions:string[];redirectTo?:string},session:Session|null,_mode:unknown){return request(`/v1/clients/${clientId}/users`,session,{method:'POST',body:JSON.stringify(input)})}
export async function updateClientUser(clientId:string,userId:string,input:{agencyId:string;role?:ClientUserRole;status?:ClientUserStatus;permissions?:string[]},session:Session|null,_mode:unknown){await request(`/v1/clients/${clientId}/users/${userId}`,session,{method:'PATCH',body:JSON.stringify(input)})}
export async function removeClientUser(clientId:string,userId:string,agencyId:string,session:Session|null,_mode:unknown){await request(`/v1/clients/${clientId}/users/${userId}?agencyId=${agencyId}`,session,{method:'DELETE'})}
