import React from 'react';
import ReactDOM from 'react-dom/client';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {createRootRoute,createRoute,createRouter,Navigate,Outlet,RouterProvider} from '@tanstack/react-router';
import {I18nProvider} from './i18n/I18nProvider';
import {AppShell} from './app/AppShell';
import {AuthProvider,useAuth} from './app/AuthProvider';
import {LoginPage} from './pages/LoginPage';
import {ClientsWorkspacePage} from './pages/clients/ClientsWorkspacePage';
import {DashboardWorkspacePage} from './pages/dashboard/DashboardWorkspacePage';
import {ModuleCatalogPage} from './pages/ModuleCatalogPage';
import {NotFoundPage} from './pages/NotFoundPage';
import {ForbiddenPage} from './pages/ForbiddenPage';
import {ReportDirectoryPage} from './pages/reports/ReportDirectoryPage';
import {ReportBuilderPage} from './pages/reports/ReportBuilderPage';
import {AuthenticationPage} from './pages/platform/AuthenticationPage';
import {WorkspacePage} from './pages/platform/WorkspacePage';
import {AgencyManagementPage} from './pages/agency/AgencyManagementPage';
import {BackendServicesPage} from './pages/backend/BackendServicesPage';
import {AgencyConnectionsPage,ClientDataSourcesPage,ConnectionManagerPage,IntegrationCatalogPage,IntegrationSchemaPage,SyncHealthPage} from './pages/integrations/IntegrationsWorkspacePage';
import {AllAdsCampaignsPage,FunnelAnalyticsPage,GoogleAdsCampaignsPage,MetaAdsCampaignsPage,TikTokAdsCampaignsPage} from './pages/integrations/PaidAdsCampaignsPage';
import './styles.css';
import './auth.css';
import './module-navigation.css';
import './platform-core.css';

document.documentElement.dataset.release='production-navigation-v1';
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:30_000,retry:1}}});
function ConfigurationError(){return <div className="center-screen"><div className="auth-loading-card"><strong>Платформа не настроена</strong><p>Для запуска нужны VITE_SUPABASE_URL и VITE_SUPABASE_PUBLISHABLE_KEY.</p></div></div>}
function Root(){const{configured,loading,session,workspace}=useAuth();if(!configured)return <ConfigurationError/>;if(loading)return <div className="center-screen"><div className="auth-loading-card">Загрузка рабочего пространства…</div></div>;if(!session)return <LoginPage/>;if(!workspace)return <div className="center-screen"><div className="auth-loading-card">Рабочее пространство недоступно.</div></div>;return <Outlet/>}
function ProtectedLayout(){return <AppShell><Outlet/></AppShell>}
const rootRoute=createRootRoute({component:Root,notFoundComponent:NotFoundPage});
const protectedRoute=createRoute({getParentRoute:()=>rootRoute,id:'protected',component:ProtectedLayout});
const indexRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/',component:ClientsWorkspacePage});
const clientsNewRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/clients/new',component:ClientsWorkspacePage});
const clientGroupsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/clients/groups',component:ClientsWorkspacePage});
const clientProfileRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/profile',component:ClientsWorkspacePage});
const clientUsersRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/users',component:ClientsWorkspacePage});
const clientSettingsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/settings',component:ClientsWorkspacePage});
const dashboardsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/dashboards',component:DashboardWorkspacePage});
const reportsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/reports',component:ReportDirectoryPage});
const reportBuilderRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/reports/$reportId',component:ReportBuilderPage});
const moduleCatalogRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/platform/modules',component:ModuleCatalogPage});
const authenticationRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/platform/authentication',component:AuthenticationPage});
const workspaceRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/platform/workspace',component:WorkspacePage});
const agencyProfileRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/settings/company',component:AgencyManagementPage});
const agencyUsersRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/settings/users',component:AgencyManagementPage});
const agencyBillingRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/settings/billing',component:AgencyManagementPage});
const onboardingRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/onboarding',component:AgencyManagementPage});
const integrationCatalogRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/data',component:IntegrationCatalogPage});
const connectionManagerRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/data/connections',component:ConnectionManagerPage});
const agencyConnectionsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/data/agency-connections',component:AgencyConnectionsPage});
const integrationSchemaRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/data/schema',component:IntegrationSchemaPage});
const syncHealthRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/data/sync-health',component:SyncHealthPage});
const clientDataSourcesRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/data',component:ClientDataSourcesPage});
const backendServiceRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/backend/$serviceId',component:BackendServicesPage});
const adsCampaignsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/ads/campaigns',component:AllAdsCampaignsPage});
const metaAdsCampaignsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/meta-ads/campaigns',component:MetaAdsCampaignsPage});
const tiktokAdsCampaignsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/tiktok-ads/campaigns',component:TikTokAdsCampaignsPage});
const googleAdsCampaignsRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/google-ads/campaigns',component:GoogleAdsCampaignsPage});
const adsFunnelRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/client/$clientId/ads/funnel',component:FunnelAnalyticsPage});
const forbiddenRoute=createRoute({getParentRoute:()=>protectedRoute,path:'/403',component:ForbiddenPage});
const loginRedirectRoute=createRoute({getParentRoute:()=>rootRoute,path:'/login',component:()=> <Navigate to="/"/>});
const routeTree=rootRoute.addChildren([protectedRoute.addChildren([indexRoute,clientsNewRoute,clientGroupsRoute,clientProfileRoute,clientUsersRoute,clientSettingsRoute,dashboardsRoute,reportsRoute,reportBuilderRoute,moduleCatalogRoute,authenticationRoute,workspaceRoute,agencyProfileRoute,agencyUsersRoute,agencyBillingRoute,onboardingRoute,integrationCatalogRoute,connectionManagerRoute,agencyConnectionsRoute,integrationSchemaRoute,syncHealthRoute,clientDataSourcesRoute,backendServiceRoute,adsCampaignsRoute,metaAdsCampaignsRoute,tiktokAdsCampaignsRoute,googleAdsCampaignsRoute,adsFunnelRoute,forbiddenRoute]),loginRedirectRoute]);
const router=createRouter({routeTree,defaultPreload:'intent'});
declare module '@tanstack/react-router'{interface Register{router:typeof router}}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><I18nProvider><AuthProvider><RouterProvider router={router}/></AuthProvider></I18nProvider></QueryClientProvider></React.StrictMode>);
