import type{Session}from'@supabase/supabase-js';
export type ReportBlockType='section'|'text'|'image'|'widget'|'page_break';
export interface ReportBlock{id?:string;type:ReportBlockType;title:string;content:Record<string,unknown>;settings:Record<string,unknown>}
export interface ReportPage{id?:string;title:string;settings:Record<string,unknown>;blocks:ReportBlock[]}
export interface ReportDocument{id:string;agencyId:string;clientId:string|null;name:string;description:string;status:string;revision:number;settings:Record<string,unknown>;branding:Record<string,unknown>;updatedAt:string;pages:ReportPage[]}
export interface ReportWidgetOption{id:string;title:string;type:string;dashboardName:string}
const baseUrl=()=>import.meta.env.VITE_REPORT_API_URL?.replace(/\/$/,'');
async function request<T>(path:string,session:Session|null,init?:RequestInit){const base=baseUrl();if(!base||!session)throw new Error('REPORT_API_NOT_CONFIGURED');const response=await fetch(`${base}${path}`,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`,...init?.headers}});if(!response.ok)throw new Error(await response.text()||`REPORT_API_${response.status}`);return response.json() as Promise<T>}
const demoDoc=(reportId:string,agencyId:string):ReportDocument=>({id:reportId,agencyId,clientId:'amanat-med',name:'Еженедельный отчёт Amanat Med',description:'Реклама, лиды и выручка.',status:'draft',revision:1,settings:{pageSize:'A4',orientation:'portrait',showHeader:true,showFooter:true},branding:{primaryColor:'#2563eb'},updatedAt:new Date().toISOString(),pages:[{title:'Обложка',settings:{cover:true},blocks:[{type:'section',title:'Результаты недели',content:{subtitle:'Ключевые показатели маркетинга'},settings:{}},{type:'text',title:'Введение',content:{text:'Отчёт подготовлен автоматически на основе подключённых источников.'},settings:{}}]}]});
let demoDocuments=new Map<string,ReportDocument>();
export async function getReportDocument(reportId:string,agencyId:string,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl()){const key=`${agencyId}:${reportId}`;if(!demoDocuments.has(key))demoDocuments.set(key,demoDoc(reportId,agencyId));return structuredClone(demoDocuments.get(key)!)}return request<ReportDocument>(`/v1/report-builder/${reportId}?agencyId=${encodeURIComponent(agencyId)}`,session)}
export async function saveReportDocument(document:ReportDocument,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl()){const saved={...structuredClone(document),revision:document.revision+1,updatedAt:new Date().toISOString()};demoDocuments.set(`${document.agencyId}:${document.id}`,saved);return saved}return request<ReportDocument>(`/v1/report-builder/${document.id}`,session,{method:'PUT',body:JSON.stringify({agencyId:document.agencyId,revision:document.revision,name:document.name,description:document.description,settings:document.settings,branding:document.branding,pages:document.pages})})}
export async function listReportWidgets(reportId:string,agencyId:string,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl())return[{id:'demo-widget-spend',title:'Расход',type:'stat',dashboardName:'Marketing overview'},{id:'demo-widget-leads',title:'Лиды',type:'line',dashboardName:'Marketing overview'}];return(request<{items:ReportWidgetOption[]}>(`/v1/report-builder/${reportId}/widgets?agencyId=${encodeURIComponent(agencyId)}`,session)).then(result=>result.items)}
