import type{Session}from'@supabase/supabase-js';

export type ReportStatus='draft'|'scheduled'|'sent'|'failed'|'archived';
export interface ReportFolder{id:string;agencyId:string;name:string;color:string;sortOrder:number;createdAt:string;updatedAt:string}
export interface ReportItem{id:string;agencyId:string;clientId:string|null;folderId:string|null;name:string;description:string;status:ReportStatus;schedule:Record<string,unknown>;recipients:unknown[];lastGeneratedAt:string|null;nextRunAt:string|null;createdAt:string;updatedAt:string;clientName:string|null;folderName:string|null}
export interface ReportFilters{clientId?:string;status?:ReportStatus;folderId?:string;search?:string}
export interface CreateReportInput{agencyId:string;clientId?:string|null;folderId?:string|null;name:string;description?:string;status?:ReportStatus;schedule?:Record<string,unknown>;recipients?:unknown[];nextRunAt?:string|null}

const demoReports:ReportItem[]=[
{id:'demo-report-1',agencyId:'demo-agency',clientId:'amanat-med',folderId:null,name:'Еженедельный отчёт Amanat Med',description:'Реклама, лиды, записи и выручка за неделю.',status:'scheduled',schedule:{frequency:'weekly'},recipients:['marketing@amanatmed.kz'],lastGeneratedAt:'2026-08-04T04:00:00Z',nextRunAt:'2026-08-11T04:00:00Z',createdAt:'2026-08-01T08:00:00Z',updatedAt:'2026-08-04T04:00:00Z',clientName:'Amanat Med',folderName:null},
{id:'demo-report-2',agencyId:'demo-agency',clientId:'demo-clinic',folderId:null,name:'Отчёт по платному трафику',description:'Meta Ads и TikTok Ads по кампаниям.',status:'draft',schedule:{},recipients:[],lastGeneratedAt:null,nextRunAt:null,createdAt:'2026-08-03T09:00:00Z',updatedAt:'2026-08-05T05:30:00Z',clientName:'Demo Clinic',folderName:null},
];
let localDemoReports=[...demoReports];
const baseUrl=()=>import.meta.env.VITE_REPORT_API_URL?.replace(/\/$/,'');
async function request<T>(path:string,session:Session|null,init?:RequestInit):Promise<T>{const base=baseUrl();if(!base||!session)throw new Error('REPORT_API_NOT_CONFIGURED');const response=await fetch(`${base}${path}`,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`,...init?.headers}});if(!response.ok){const detail=await response.text();throw new Error(detail||`REPORT_API_${response.status}`)}return response.json() as Promise<T>}
export async function listReports(agencyId:string,filters:ReportFilters,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl()){const search=filters.search?.trim().toLowerCase();return localDemoReports.filter(item=>item.agencyId===agencyId&&(!filters.clientId||item.clientId===filters.clientId)&&(!filters.status||item.status===filters.status)&&(!filters.folderId||item.folderId===filters.folderId)&&(!search||item.name.toLowerCase().includes(search)||item.description.toLowerCase().includes(search)))}const params=new URLSearchParams({agencyId});if(filters.clientId)params.set('clientId',filters.clientId);if(filters.status)params.set('status',filters.status);if(filters.folderId)params.set('folderId',filters.folderId);if(filters.search)params.set('search',filters.search);return(request<{items:ReportItem[]}>(`/v1/reports?${params}`,session)).then(result=>result.items)}
export async function listReportFolders(agencyId:string,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl())return[];return(request<{items:ReportFolder[]}>(`/v1/report-folders?agencyId=${encodeURIComponent(agencyId)}`,session)).then(result=>result.items)}
export async function createReport(input:CreateReportInput,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl()){const now=new Date().toISOString();const item:ReportItem={id:`demo-${crypto.randomUUID()}`,agencyId:input.agencyId,clientId:input.clientId??null,folderId:input.folderId??null,name:input.name,description:input.description??'',status:input.status??'draft',schedule:input.schedule??{},recipients:input.recipients??[],lastGeneratedAt:null,nextRunAt:input.nextRunAt??null,createdAt:now,updatedAt:now,clientName:null,folderName:null};localDemoReports=[item,...localDemoReports];return item}return request<ReportItem>('/v1/reports',session,{method:'POST',body:JSON.stringify(input)})}
export async function archiveReport(id:string,agencyId:string,session:Session|null,mode:'supabase'|'demo'){if(mode==='demo'||!baseUrl()){localDemoReports=localDemoReports.map(item=>item.id===id?{...item,status:'archived',updatedAt:new Date().toISOString()}:item);return}await request(`/v1/reports/${id}/archive`,session,{method:'POST',body:JSON.stringify({agencyId})})}
