import {BadRequestException,Body,Controller,Get,Headers,Injectable,OnModuleDestroy,OnModuleInit,Param,Post,Put,Query} from '@nestjs/common';
import {z} from 'zod';
import {Db} from './db.js';
import {AccessService,verifyUserJwt} from './security.js';

const uuid=z.string().uuid();
const channel=z.enum(['email','in_app','slack','telegram','webhook']);
const recipient=z.object({id:uuid.optional(),channel,address:z.string().trim().min(1).max(2000),name:z.string().trim().max(160).default(''),enabled:z.boolean().default(true)});
const schedule=z.object({enabled:z.boolean().default(false),frequency:z.enum(['once','daily','weekly','monthly']).default('once'),timezone:z.string().trim().min(1).max(80).default('UTC'),nextRunAt:z.string().datetime().nullable().default(null),weekday:z.number().int().min(0).max(6).optional(),monthday:z.number().int().min(1).max(28).optional()});
const deliverySchema=z.object({agencyId:uuid,schedule,recipients:z.array(recipient).max(100),subject:z.string().trim().max(200).default(''),message:z.string().max(5000).default(''),includeLink:z.boolean().default(true)});
const sendSchema=z.object({agencyId:uuid,recipientIds:z.array(uuid).optional(),subject:z.string().trim().max(200).optional(),message:z.string().max(5000).optional()});
const parse=<T>(schema:z.ZodType<T>,value:unknown):T=>{const result=schema.safeParse(value);if(!result.success)throw new BadRequestException(result.error.flatten());return result.data};
const object=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};

type ReportRow={id:string;agency_id:string;client_id:string|null;name:string;description:string;status:string;schedule:Record<string,unknown>;recipients:unknown[];next_run_at:string|null;last_generated_at:string|null};
type JobRow={id:string;channel:string;recipient:string;state:string;attempts:number;max_attempts:number;run_after:string;last_error:unknown;created_at:string;updated_at:string;finished_at:string|null;provider_message_id:string|null;delivery_status:string|null};

function nextOccurrence(current:string,frequency:string){const date=new Date(current);if(frequency==='daily')date.setUTCDate(date.getUTCDate()+1);else if(frequency==='weekly')date.setUTCDate(date.getUTCDate()+7);else if(frequency==='monthly')date.setUTCMonth(date.getUTCMonth()+1);else return null;return date.toISOString()}

@Injectable()
export class ReportDeliveryScheduler implements OnModuleInit,OnModuleDestroy{
  private timer?:NodeJS.Timeout;private running=false;
  constructor(private readonly db:Db){}
  onModuleInit(){this.timer=setInterval(()=>void this.tick(),60_000);this.timer.unref();void this.tick()}
  onModuleDestroy(){if(this.timer)clearInterval(this.timer)}
  async tick(){if(this.running)return;this.running=true;try{const due=await this.db.query<ReportRow>(`select id,agency_id,client_id,name,description,status,schedule,recipients,next_run_at,last_generated_at from public.reports where status='scheduled' and next_run_at is not null and next_run_at<=now() order by next_run_at limit 25`);for(const report of due.rows)await enqueueReport(this.db,report,report.next_run_at??new Date().toISOString())}finally{this.running=false}}
}

async function getReport(db:Db,id:string,agencyId:string){const result=await db.query<ReportRow>(`select id,agency_id,client_id,name,description,status,schedule,recipients,next_run_at,last_generated_at from public.reports where id=$1 and agency_id=$2`,[id,agencyId]);if(!result.rows[0])throw new BadRequestException('REPORT_NOT_FOUND');return result.rows[0]}
async function enqueueReport(db:Db,report:ReportRow,scheduledAt:string,recipientIds?:string[],overrides?:{subject?:string;message?:string}){const configuration=object(report.schedule),allRecipients=Array.isArray(report.recipients)?report.recipients:[];const selected=allRecipients.filter((value):value is Record<string,unknown>=>Boolean(value&&typeof value==='object'&&!Array.isArray(value))).filter(value=>value.enabled!==false&&(!recipientIds||recipientIds.includes(String(value.id))));if(!selected.length)throw new BadRequestException('REPORT_RECIPIENTS_REQUIRED');await db.transaction(async client=>{for(const target of selected){const targetChannel=channel.parse(target.channel),address=String(target.address??'').trim();if(!address)continue;const payload={reportId:report.id,reportName:report.name,description:report.description,subject:overrides?.subject??configuration.subject??report.name,message:overrides?.message??configuration.message??'',reportUrl:configuration.includeLink===false?null:`/reports/${report.id}`,scheduledAt};const dedupe=`report:${report.id}:${scheduledAt}:${targetChannel}:${address}`;await client.query(`insert into public.notification_jobs(agency_id,client_id,channel,recipient,template_key,payload,run_after,dedupe_key) values($1,$2,$3,$4,'report.delivery',$5,now(),$6) on conflict(dedupe_key) where dedupe_key is not null and state in ('queued','running') do nothing`,[report.agency_id,report.client_id,targetChannel,address,payload,dedupe])}const scheduleConfig=object(report.schedule),frequency=String(scheduleConfig.frequency??'once'),next=nextOccurrence(scheduledAt,frequency);await client.query(`update public.reports set status=$3,last_generated_at=now(),next_run_at=$4,updated_at=now() where id=$1 and agency_id=$2`,[report.id,report.agency_id,next?'scheduled':'sent',next])});return{queued:selected.length}}

@Controller('v1/reports/:reportId/delivery')
export class ReportDeliveryController{
  constructor(private readonly db:Db,private readonly access:AccessService){}
  private async authorized(auth:string,reportId:string,agencyId:string,manage=false){const user=await verifyUserJwt(auth);parse(uuid,reportId);parse(uuid,agencyId);await this.access.requirePermission(user.userId,agencyId,manage?'reports.manage':'reports.read');return getReport(this.db,reportId,agencyId)}
  @Get() async get(@Headers('authorization')auth:string,@Param('reportId')reportId:string,@Query('agencyId')agencyId:string){const report=await this.authorized(auth,reportId,agencyId);const configuration=object(report.schedule);return{reportId:report.id,status:report.status,schedule:{enabled:report.status==='scheduled',frequency:configuration.frequency??'once',timezone:configuration.timezone??'UTC',nextRunAt:report.next_run_at,weekday:configuration.weekday,monthday:configuration.monthday},recipients:report.recipients,subject:configuration.subject??'',message:configuration.message??'',includeLink:configuration.includeLink!==false,lastGeneratedAt:report.last_generated_at}}
  @Put() async save(@Headers('authorization')auth:string,@Param('reportId')reportId:string,@Body()body:unknown){const input=parse(deliverySchema,body),report=await this.authorized(auth,reportId,input.agencyId,true);if(input.schedule.enabled&&!input.schedule.nextRunAt)throw new BadRequestException('NEXT_RUN_AT_REQUIRED');const stored={frequency:input.schedule.frequency,timezone:input.schedule.timezone,weekday:input.schedule.weekday,monthday:input.schedule.monthday,subject:input.subject,message:input.message,includeLink:input.includeLink};await this.db.query(`update public.reports set status=$3,schedule=$4,recipients=$5,next_run_at=$6,updated_at=now() where id=$1 and agency_id=$2`,[report.id,input.agencyId,input.schedule.enabled?'scheduled':'draft',stored,input.recipients,input.schedule.enabled?input.schedule.nextRunAt:null]);return this.get(auth,reportId,input.agencyId)}
  @Post('send') async send(@Headers('authorization')auth:string,@Param('reportId')reportId:string,@Body()body:unknown){const input=parse(sendSchema,body),report=await this.authorized(auth,reportId,input.agencyId,true);return enqueueReport(this.db,report,new Date().toISOString(),input.recipientIds,{subject:input.subject,message:input.message})}
  @Get('history') async history(@Headers('authorization')auth:string,@Param('reportId')reportId:string,@Query('agencyId')agencyId:string){await this.authorized(auth,reportId,agencyId);const result=await this.db.query<JobRow>(`select j.id,j.channel,j.recipient,j.state,j.attempts,j.max_attempts,j.run_after,j.last_error,j.created_at,j.updated_at,j.finished_at,d.provider_message_id,d.status delivery_status from public.notification_jobs j left join lateral(select provider_message_id,status from public.notification_deliveries where job_id=j.id order by attempt desc limit 1)d on true where j.agency_id=$1 and j.payload->>'reportId'=$2 order by j.created_at desc limit 250`,[agencyId,reportId]);return{items:result.rows.map(row=>({id:row.id,channel:row.channel,recipient:row.recipient,state:row.state,attempts:row.attempts,maxAttempts:row.max_attempts,runAfter:row.run_after,lastError:row.last_error,createdAt:row.created_at,updatedAt:row.updated_at,finishedAt:row.finished_at,providerMessageId:row.provider_message_id,deliveryStatus:row.delivery_status}))}}
}
