import type{ModuleDefinition,ModuleDomain,ModuleStatus,ModuleSurface}from'./types';

const module=(id:string,name:string,description:string,submodules:string[],options:Partial<Pick<ModuleDefinition,'status'|'surface'|'route'|'permissions'|'entitlements'|'dependencies'>>={}):ModuleDefinition=>({id,name,description,submodules,status:options.status??'planned',surface:options.surface??'workspace',route:options.route,permissions:options.permissions??[],entitlements:options.entitlements??[],dependencies:options.dependencies??[]});

export const moduleDomains:ModuleDomain[]=[
{id:'platform-core',name:'Platform Core',description:'Общее ядро всех продуктов IMDS.',modules:[
module('authentication','Authentication','Аутентификация и жизненный цикл сессий.',['Email/password','Magic Link','Google OAuth','Microsoft OAuth','Password Recovery','Email Confirmation','MFA/TOTP','Refresh Sessions','Session Management','Device Management','Login History','Logout From All Devices'],{status:'development',surface:'shared',permissions:['auth.session'],dependencies:[]}),
module('workspace','Workspace','Контекст пользователя, tenant и активного продукта.',['Workspace Bootstrap','Current User','Active Agency','Agency Switcher','Active Client','Client Switcher','Product Context','Available Modules','Workspace Preferences','Recent Items'],{status:'development',surface:'shared',permissions:['workspace.read'],dependencies:['authentication']}),
module('multi-tenancy','Multi-Tenancy','Изоляция агентств, клиентов, API, jobs и storage.',['Agency Isolation','Client Isolation','Memberships','Client Access','Tenant Context','RLS Policies','Tenant-Scoped API','Tenant-Scoped Jobs','Tenant-Scoped Storage'],{status:'development',surface:'shared',permissions:['tenant.read'],dependencies:['workspace']}),
module('permissions','Roles and Permissions','Роли и гранулярные права доступа.',['Roles','Permission Registry','Role Permissions','User Overrides','Client-Level Permissions','Module Permissions','Route Guards','Action Guards','API Authorization','Permission Audit'],{status:'development',surface:'shared',permissions:['permissions.read'],dependencies:['multi-tenancy']}),
module('entitlements','Entitlements','Тарифные ограничения и доступность возможностей.',['Plan Limits','Module Availability','Client Limits','User Limits','Integration Limits','Report Limits','Storage Limits','Data Retention','Sync Frequency','AI Usage Limits'],{surface:'shared',permissions:['billing.read'],dependencies:['workspace']}),
module('feature-flags','Feature Flags','Безопасный rollout функций.',['Global Flags','Tenant Flags','User Flags','Beta Access','Percentage Rollout','Experimental Features','Emergency Kill Switch'],{surface:'shared',permissions:['features.read'],dependencies:['workspace']}),
module('branding','Branding','White-label оформление продуктов.',['Agency Logo','Client Logo','Colors','Typography','Favicon','Email Branding','Report Branding','Portal Branding','Custom Domain','White Label'],{surface:'shared',permissions:['branding.read'],dependencies:['workspace']}),
module('audit','Audit','Аудит действий и событий безопасности.',['Activity Log','User Actions','Data Changes','Security Events','Impersonation Events','API Activity','Export Activity','Login Activity'],{surface:'shared',permissions:['audit.read'],dependencies:['authentication','multi-tenancy']})]},
{id:'agency-management',name:'Agency Management',description:'Управление агентством, командой и подпиской.',modules:[
module('agency-profile','Agency Profile','Профиль и настройки агентства.',['Company Details','Contact Details','Legal Information','Country','Language','Timezone','Currency','Working Hours','Agency Markup','Default Settings'],{route:'/settings/company',permissions:['agency.read']}),
module('users-teams','Users and Teams','Пользователи, команды и назначения клиентов.',['User Directory','Invitations','Roles','Teams','Account Managers','Client Assignment','User Status','User Profile','Access History','Deactivation'],{route:'/settings/users',permissions:['users.read'],dependencies:['permissions']}),
module('billing','Billing and Subscription','Тарифы, подписка и использование.',['Plans','Subscription','Trial','Usage','Limits','Payment Method','Invoices','Coupons','Upgrade','Downgrade','Cancellation'],{route:'/settings/billing',permissions:['billing.read'],dependencies:['entitlements']}),
module('agency-onboarding','Agency Onboarding','Пошаговая настройка агентства.',['Welcome Flow','Company Setup','Branding Setup','First Client','First Integration','First Dashboard','First Report','Setup Progress','Guided Checklist'],{route:'/onboarding',permissions:['workspace.read'],dependencies:['agency-profile','clients','integration-catalog','dashboard-directory','report-directory']})]},
{id:'clients',name:'Clients',description:'Управление клиентами агентства.',modules:[
module('client-directory','Client Directory','Каталог клиентов.',['Client List','Search','Filters','Sorting','Pagination','Groups','Status','Bulk Selection','Client Summary','Last Activity'],{status:'development',route:'/clients',permissions:['clients.read']}),
module('client-creation','Client Creation','Создание нового клиента.',['Company','Domain','Logo','Brand Color','Country','Language','Timezone','Currency','Start Date','Client Group','Account Manager','Client Template'],{route:'/clients/new',permissions:['clients.manage'],dependencies:['client-directory']}),
module('client-profile','Client Profile','Карточка клиента и его бизнес-контекст.',['General Information','Contacts','Website','Industry','Goals','Notes','CRM Mapping','Analytics Settings','Attribution Settings','Tracking Settings'],{route:'/client/:clientId/profile',permissions:['clients.read'],dependencies:['client-directory']}),
module('client-users','Client Users','Доступ пользователей клиента.',['Client Invitations','Client Roles','Dashboard Access','Report Access','Data Access','Portal Access','User Restrictions','Login History'],{route:'/client/:clientId/users',permissions:['client_users.read'],dependencies:['client-profile','permissions']}),
module('client-settings','Client Settings','Настройки аналитики и брендинга клиента.',['Client Details','Agency Markup','Logos','Rank Tracker','Import','Export','Timezone','Currency','Retention','Attribution Model','UTM Settings'],{route:'/client/:clientId/settings',permissions:['clients.manage'],dependencies:['client-profile']}),
module('client-groups','Client Groups','Группировка клиентов.',['Group Creation','Group Membership','Industry Groups','Region Groups','Manager Groups','Tags','Group Reporting','Group Permissions'],{route:'/clients/groups',permissions:['clients.manage'],dependencies:['client-directory']})]},
{id:'integrations',name:'Integrations and Data Sources',description:'Каталог, подключения и состояние источников.',modules:[
module('integration-catalog','Integration Catalog','Каталог внешних систем.',['Analytics','Paid Ads','SEO','Social','Ecommerce','Email','CRM','Call Tracking','Local','Databases','Files','Custom Integrations'],{status:'development',route:'/data',permissions:['integrations.read']}),
module('connection-manager','Connection Manager','Подключение и переподключение источников.',['OAuth','API Key','Basic Auth','Service Account','Database Credentials','File Upload','Credential Validation','Account Discovery','Account Selection','Client Attachment','Reconnect','Disconnect'],{status:'development',route:'/data/connections',permissions:['integrations.manage'],dependencies:['integration-catalog']}),
module('agency-connections','Agency Connections','Общие OAuth-подключения агентства.',['Shared OAuth Grants','Connected Accounts','Available Accounts','Client Attachments','Credential Rotation','Token Refresh','Revocation','Connection Ownership'],{route:'/data/agency-connections',permissions:['integrations.manage'],dependencies:['connection-manager']}),
module('data-source-management','Data Source Management','Управление подключёнными источниками.',['Source List','Source Status','External Account ID','Last Sync','Next Sync','Sync Depth','Manual Sync','Backfill','Pause','Resume','Reconnect','Delete'],{route:'/client/:clientId/data',permissions:['integrations.read'],dependencies:['connection-manager']}),
module('integration-schema','Integration Schema','Схема сущностей и метрик провайдера.',['Entities','Dimensions','Metrics','Breakdowns','Filters','Supported Date Range','Attribution Windows','Rate Limits','Provider Errors','Provider Metadata'],{surface:'shared',permissions:['integrations.read'],dependencies:['integration-catalog']}),
module('sync-health','Sync Health','Диагностика свежести и ошибок данных.',['Queue Status','Current Job','Progress','Last Success','Last Error','Retry Count','Token Status','Data Freshness','Sync History','Diagnostics'],{route:'/data/sync-health',permissions:['integrations.read'],dependencies:['data-source-management']})]},
{id:'data-collection',name:'Data Collection',description:'Фоновые процессы получения и нормализации данных.',modules:[
module('sync-dispatcher','Sync Dispatcher','Планирование синхронизаций.',['Incremental Sync','Daily Reconciliation','Historical Backfill','Manual Sync','Retry Scheduling','Priority Scheduling','Job Deduplication','Stale Job Recovery'],{status:'development',surface:'backend',dependencies:['data-source-management']}),
module('sync-worker','Sync Worker','Исполнение sync jobs.',['Job Claiming','Lock Ownership','Credential Retrieval','Provider Request','Pagination','Rate-Limit Handling','Normalization','Validation','Upsert','Completion','Failure','Retry'],{status:'development',surface:'backend',dependencies:['sync-dispatcher','provider-adapters']}),
module('provider-adapters','Provider Adapters','Единый SDK интеграций.',['Meta Adapter','TikTok Adapter','Google Ads Adapter','Analytics Adapter','CRM Adapter','SEO Adapter','Ecommerce Adapter','Custom Adapter SDK'],{status:'development',surface:'backend',dependencies:['integration-schema']}),
module('raw-data-processing','Raw Data Processing','Нормализация и контроль качества.',['Raw Response Validation','Normalization','Dimension Upsert','Metric Upsert','Currency Normalization','Timezone Normalization','Deduplication','Data Quality Checks'],{surface:'backend',dependencies:['sync-worker']}),
module('crm-enrichment','CRM Enrichment','Обогащение рекламных данных результатами CRM.',['CRM Leads','Qualified Leads','Appointments','Arrived Patients','Sales','Revenue','Lead Matching','Phone Matching','UTM Matching','Conversation Matching','Attribution Key','Attribution Rules'],{surface:'backend',dependencies:['raw-data-processing']})]},
{id:'advertising-analytics',name:'Advertising Analytics',description:'Аналитика рекламных сущностей и воронки.',modules:[
module('ad-accounts','Ad Accounts','Аналитика рекламных кабинетов.',['Account List','Currency','Timezone','Status','Spend Limit','Account Summary'],{route:'/client/:clientId/:integration/accounts',permissions:['analytics.read'],dependencies:['data-source-management']}),
module('campaigns','Campaigns','Кампании и ключевые показатели.',['Campaign List','Campaign Status','Budget','Spend','Impressions','Reach','Clicks','CTR','CPC','CPM','Leads','CPL','Sales','CPA','Revenue','ROAS'],{status:'development',route:'/client/:clientId/:integration/campaigns',permissions:['analytics.read'],dependencies:['ad-accounts']}),
module('ad-groups','Ad Groups / Ad Sets','Группы объявлений.',['Group List','Status','Budget','Bid Strategy','Optimization','Audience','Placement','Performance','Campaign Drill-Down'],{route:'/client/:clientId/:integration/ad-groups',permissions:['analytics.read'],dependencies:['campaigns']}),
module('ads-creatives','Ads and Creatives','Объявления и креативы.',['Ad List','Image','Video','Headline','Description','CTA','Spend','Engagement','Leads','Sales','Creative Comparison'],{route:'/client/:clientId/:integration/ads',permissions:['analytics.read'],dependencies:['ad-groups']}),
module('demographics','Demographics','Разрезы аудитории.',['Age','Gender','Country','Region','City','Device','Placement','Platform','Operating System'],{route:'/client/:clientId/:integration/demographics',permissions:['analytics.read'],dependencies:['campaigns']}),
module('funnel-analytics','Funnel Analytics','Воронка от показов до выручки.',['Impressions','Clicks','Leads','Qualified Leads','Appointments','Arrivals','Sales','Revenue','Conversion Rates','Drop-Off Analysis'],{route:'/client/:clientId/funnel',permissions:['analytics.read'],dependencies:['campaigns','crm-enrichment']}),
module('attribution','Attribution','Модели атрибуции.',['First Click','Last Click','Linear','Position Based','Custom Attribution','Attribution Window','Cross-Platform Matching','Offline Conversion Import'],{route:'/client/:clientId/settings/attribution',permissions:['analytics.manage'],dependencies:['crm-enrichment']})]},
{id:'dashboards',name:'Dashboards',description:'Интерактивные аналитические пространства.',modules:[
module('dashboard-directory','Dashboard Directory','Список и управление дашбордами.',['Dashboard List','Create','Rename','Duplicate','Delete','Archive','Reorder','Default Dashboard','Smart Dashboard'],{status:'development',route:'/client/:clientId/dashboards',permissions:['dashboards.read']}),
module('dashboard-builder','Dashboard Builder','Редактор сетки и секций.',['12-Column Grid','Drag and Drop','Resize','Sections','Layout Save','Edit Mode','View Mode','Preview','Undo','Redo','Copy','Paste','Duplicate','Multi-Select'],{status:'development',route:'/client/:clientId/dashboards/:dashboardId',permissions:['dashboards.manage'],dependencies:['dashboard-directory']}),
module('widget-builder','Widget Builder','Создание аналитических виджетов.',['Stat','Scorecard','Line','Area','Bar','Stacked Bar','Pie','Donut','Table','Funnel','Progress','Gauge','Text','Image','Iframe','Custom View','AI Insight'],{status:'development',permissions:['dashboards.manage'],dependencies:['dashboard-builder','integration-schema']}),
module('widget-configuration','Widget Configuration','Настройка источников, метрик и отображения.',['Integration','Entity','Metric','Dimension','Aggregation','Breakdown','Date Range','Comparison','Filters','Sort','Limit','Formatting','Color','Title'],{permissions:['dashboards.manage'],dependencies:['widget-builder']}),
module('dashboard-filters','Dashboard Filters','Глобальные фильтры дашборда.',['Date Filter','Integration Filter','Campaign Filter','Account Filter','Device Filter','Region Filter','Custom Filters','Filter Chips','Clear All'],{permissions:['dashboards.read'],dependencies:['dashboard-builder']}),
module('dashboard-sharing','Dashboard Sharing','Экспорт и публикация дашбордов.',['Public Link','Password','Expiration','Download PDF','Download XLS','Email','Add to Report','Fullscreen','Embed'],{permissions:['dashboards.share'],dependencies:['dashboard-builder','export-center']})]},
{id:'reports',name:'Reports',description:'Конструктор и доставка отчётов.',modules:[
module('report-directory','Report Directory','Каталог отчётов.',['All Reports','Draft','Scheduled','Sent','Failed','Archived','Search','Filters','Folders'],{route:'/reports',permissions:['reports.read']}),
module('report-builder','Report Builder','Многостраничный редактор отчётов.',['Cover Page','Multiple Pages','Sections','Widgets','Text Blocks','Images','Page Breaks','Header','Footer','Branding','Preview'],{route:'/client/:clientId/reports/:reportId',permissions:['reports.manage'],dependencies:['report-directory','widget-builder']}),
module('report-scheduling','Report Scheduling','Расписание генерации.',['Daily','Weekly','Monthly','Quarterly','Day','Time','Timezone','Start Date','End Date','Pause','Resume'],{permissions:['reports.manage'],dependencies:['report-builder']}),
module('report-recipients','Report Recipients','Получатели и шаблон письма.',['To','CC','BCC','Client Users','Recipient Groups','Custom Subject','Custom Message','Language'],{permissions:['reports.manage'],dependencies:['report-builder','client-users']}),
module('report-delivery','Report Delivery','Каналы доставки.',['PDF','Shared Link','Email Attachment','Client Portal','Password Protection','Link Expiration'],{permissions:['reports.send'],dependencies:['report-scheduling','report-recipients','export-worker']}),
module('report-history','Report History','История генерации и отправки.',['Delivery Status','Sent Date','Recipients','Generated File','Version','Error','Retry','Open Tracking'],{permissions:['reports.read'],dependencies:['report-delivery']})]},
{id:'cross-client',name:'Cross-Client Analytics',description:'Агрегация и сравнение нескольких клиентов.',modules:[
module('rollup-dashboards','Roll-Up Dashboards','Сводная аналитика агентства.',['Multi-Client Metrics','Client Comparison','Agency Totals','Averages','Rankings','Groups','Trends','Manager Performance'],{route:'/rollups',permissions:['rollups.read'],dependencies:['client-groups','dashboard-builder']}),
module('rollup-reports','Roll-Up Reports','Сводные отчёты.',['Multi-Client Reports','Agency Reports','Group Reports','Manager Reports','Scheduled Delivery','Roll-Up Templates'],{route:'/rollups/reports',permissions:['rollups.manage'],dependencies:['rollup-dashboards','report-builder']}),
module('benchmarks','Benchmarks','Сравнение с историей и рынком.',['Industry Benchmarks','Agency Benchmarks','Historical Benchmarks','Percentiles','Median','Top 10%','Client Comparison','Benchmark Alerts'],{route:'/client/:clientId/benchmarks',permissions:['benchmarks.read'],dependencies:['campaigns']})]},
{id:'kpis',name:'KPIs and Goals',description:'Цели, прогресс и оповещения.',modules:[
module('kpi-management','KPI Management','Определение KPI.',['KPI List','Metric Selection','Target','Minimum','Maximum','Period','Client','Integration','Responsible User'],{route:'/kpis',permissions:['kpis.read'],dependencies:['integration-schema']}),
module('kpi-progress','KPI Progress','Состояние достижения целей.',['Current Value','Target Value','Progress','Trend','Forecast','On Track','At Risk','Missed','Achieved'],{route:'/client/:clientId/kpis',permissions:['kpis.read'],dependencies:['kpi-management']}),
module('kpi-alerts','KPI Alerts','Уведомления при отклонениях.',['Threshold','Email','In-App','Slack','Telegram','Webhook','Alert History'],{permissions:['kpis.manage'],dependencies:['kpi-management','notification-channels']})]},
{id:'views-custom-data',name:'Views and Custom Data',description:'Кросс-платформенные таблицы и вычисляемые показатели.',modules:[
module('view-builder','View Builder','Конструктор объединённых таблиц.',['Blank View','AI Prompt','Suggested Views','Clone View','Multiple Sources','Dimension','Metrics','Filters','Sorting','Preview','Save'],{route:'/client/:clientId/views/new',permissions:['views.manage'],dependencies:['integration-schema']}),
module('view-management','View Management','Управление сохранёнными представлениями.',['View List','Edit','Duplicate','Delete','Share','Export','Add to Dashboard','Add to Report'],{route:'/client/:clientId/views',permissions:['views.read'],dependencies:['view-builder']}),
module('custom-metrics','Custom Metrics','Вычисляемые метрики.',['Formula Builder','Dependencies','Validation','Formatting','Client Scope','Agency Scope','Metric Preview','Version History'],{route:'/data/custom-metrics',permissions:['metrics.manage'],dependencies:['integration-schema']}),
module('custom-dimensions','Custom Dimensions','Вычисляемые измерения.',['Dimension Definition','Mapping Rules','Lookup Tables','Categories','Calculated Dimensions','Reusable Dimensions'],{route:'/data/custom-dimensions',permissions:['dimensions.manage'],dependencies:['integration-schema']})]},
{id:'templates-automation',name:'Templates and Automation',description:'Шаблоны и массовые операции.',modules:[
module('dashboard-templates','Dashboard Templates','Шаблоны дашбордов.',['Layout','Widgets','Metrics','Filters','Integrations','Branding'],{route:'/templates/dashboards',permissions:['templates.read'],dependencies:['dashboard-builder']}),
module('report-templates','Report Templates','Шаблоны отчётов.',['Pages','Sections','Widgets','Cover','Branding','Schedule'],{route:'/templates/reports',permissions:['templates.read'],dependencies:['report-builder']}),
module('client-templates','Client Templates','Шаблоны клиентского пространства.',['Default Dashboards','Default Reports','Default KPIs','Default Settings','Default Users','Default Integrations'],{route:'/templates/clients',permissions:['templates.read'],dependencies:['client-creation']}),
module('email-templates','Email Templates','Шаблоны писем.',['Subject','Body','Variables','Branding','Localization','Preview'],{route:'/templates/emails',permissions:['templates.read'],dependencies:['branding']}),
module('bulk-operations','Bulk Operations','Массовые действия по клиентам.',['Bulk Dashboard Creation','Bulk Report Creation','Apply Template','Change Schedule','Update Clients','Archive','Delete','Progress','Results','Failed Items','Retry'],{route:'/bulk-operations',permissions:['bulk.manage'],dependencies:['client-directory','dashboard-templates','report-templates']}),
module('workflow-automation','Workflow Automation','Автоматизация на основе событий.',['Trigger','Condition','Action','Schedule','Integration Events','KPI Events','Report Events','Sync Events','Workflow History'],{route:'/automations',permissions:['automation.manage'],dependencies:['audit']})]},
{id:'files-exports',name:'Files and Exports',description:'Файлы, генерация и хранение экспортов.',modules:[
module('file-manager','File Manager','Файлы клиента и агентства.',['File Upload','Folder Structure','Client Files','Report Assets','Logos','Attachments','Search','Preview','Download','Delete','Access Control'],{route:'/files',permissions:['files.read']}),
module('export-center','Export Center','Центр экспортов.',['PDF','XLSX','CSV','PNG','Export History','Status','Requested By','Download','Expiration','Retry'],{route:'/exports',permissions:['exports.read'],dependencies:['file-manager']}),
module('export-worker','Export Worker','Фоновая генерация файлов.',['Queue','Rendering','Spreadsheet Generation','Storage Upload','Retry','Cleanup','Expiration'],{surface:'backend',dependencies:['export-center']})]},
{id:'client-portal',name:'Client Portal',description:'White-label пространство клиента.',modules:[
module('portal-authentication','Portal Authentication','Вход клиентов в портал.',['Client Login','Magic Link','Password','MFA','Session Management'],{surface:'client-portal',permissions:['portal.login'],dependencies:['authentication']}),
module('portal-dashboard','Portal Dashboard','Доступные клиенту дашборды.',['Assigned Dashboards','Date Range','Filters','Fullscreen','Export'],{surface:'client-portal',route:'/portal/dashboards',permissions:['portal.dashboards'],dependencies:['portal-authentication','dashboard-directory']}),
module('portal-reports','Portal Reports','Просмотр и скачивание отчётов.',['Report List','Report Viewer','PDF Download','Shared Reports','History'],{surface:'client-portal',route:'/portal/reports',permissions:['portal.reports'],dependencies:['portal-authentication','report-directory']}),
module('portal-collaboration','Portal Collaboration','Взаимодействие агентства и клиента.',['Comments','Mentions','Approval','Feedback','File Sharing','Support Messages'],{surface:'client-portal',permissions:['portal.collaborate'],dependencies:['portal-authentication','file-manager']}),
module('portal-branding','Portal Branding','White-label оформление портала.',['Client Logo','Agency Logo','Colors','Domain','Email Branding','Login Page'],{surface:'client-portal',permissions:['portal.branding'],dependencies:['branding']}),
module('portal-settings','Portal Settings','Настройки портала.',['Users','Permissions','Notifications','Domain','Visibility','Language','Timezone'],{surface:'client-portal',route:'/portal/settings',permissions:['portal.manage'],dependencies:['portal-authentication','portal-branding']})]},
{id:'notifications',name:'Notifications and Communication',description:'Входящие, уведомления и каналы.',modules:[
module('inbox','Inbox','Центр сообщений.',['System Messages','Client Messages','Mentions','Support Messages','Report Messages','Sync Warnings'],{route:'/inbox',permissions:['inbox.read']}),
module('notifications','Notifications','Событийные уведомления.',['Sync Failed','Token Expired','Report Ready','Report Failed','KPI Alert','Export Ready','Invitation','Billing Alert'],{route:'/notifications',permissions:['notifications.read'],dependencies:['inbox']}),
module('notification-channels','Notification Channels','Каналы доставки уведомлений.',['In-App','Email','Slack','Telegram','Webhook','SMS'],{surface:'shared',dependencies:['notifications']}),
module('notification-preferences','Notification Preferences','Персональные настройки уведомлений.',['Channel Settings','Event Settings','Quiet Hours','Frequency','Language','Digest'],{route:'/settings/notifications',permissions:['notifications.manage'],dependencies:['notification-channels']})]},
{id:'ai',name:'AI and Intelligence',description:'AI-ассистент и автоматизированные инсайты.',modules:[
module('agency-ai','AgencyAI Assistant','Диалог с данными.',['Questions About Data','Metric Explanation','Period Comparison','Root Cause Analysis','Recommendations','Natural Language Search'],{route:'/ai',permissions:['ai.use'],entitlements:['ai'],dependencies:['campaigns','report-api']}),
module('automated-insights','Automated Insights','Автоматическое обнаружение изменений.',['Spend Anomaly','Lead Drop','CPL Increase','ROAS Change','Best Campaign','Worst Campaign','Forecast','Opportunity Detection'],{permissions:['ai.use'],entitlements:['ai'],dependencies:['agency-ai']}),
module('ai-report-writer','AI Report Writer','Генерация текста отчёта.',['Executive Summary','Performance Summary','Problems','Recommendations','Multilingual Text','Tone Selection'],{permissions:['ai.use'],entitlements:['ai'],dependencies:['report-builder','agency-ai']}),
module('ai-dashboard-builder','AI Dashboard Builder','Создание дашборда по запросу.',['Prompt to Dashboard','Widget Selection','Metric Selection','Layout Generation','Filter Generation'],{permissions:['ai.use'],entitlements:['ai'],dependencies:['dashboard-builder','agency-ai']}),
module('ai-view-builder','AI View Builder','Создание таблиц по запросу.',['Prompt to Table','Source Selection','Dimension Selection','Metric Selection','Query Explanation'],{permissions:['ai.use'],entitlements:['ai'],dependencies:['view-builder','agency-ai']}),
module('ai-governance','AI Governance','Безопасность и контроль AI.',['Usage Limits','Prompt Logging','Sensitive Data Protection','Model Selection','Human Approval','AI Audit'],{surface:'shared',permissions:['ai.admin'],dependencies:['audit','entitlements']})]},
{id:'search',name:'Search',description:'Глобальный поиск и командная палитра.',modules:[
module('global-search','Global Search','Поиск по сущностям платформы.',['Clients','Dashboards','Reports','Campaigns','Integrations','Metrics','Users','Settings','Files'],{route:'/search',permissions:['search.use'],dependencies:['client-directory','dashboard-directory','report-directory']}),
module('command-palette','Command Palette','Быстрые действия с клавиатуры.',['Navigation','Create Client','Create Report','Create Dashboard','Connect Integration','Start Export','Quick Actions','Keyboard Shortcuts'],{permissions:['search.use'],dependencies:['global-search']})]},
{id:'developer-platform',name:'Developer Platform',description:'API, webhooks и MCP.',modules:[
module('api-keys','API Keys','Управление ключами доступа.',['Generate','Rotate','Revoke','Scopes','Expiration','Last Used','Usage Statistics'],{route:'/settings/api/keys',permissions:['api_keys.manage']}),
module('api-documentation','API Documentation','Документация внешнего API.',['Overview','Authentication','Requests','Responses','Errors','Pagination','Rate Limits','Examples'],{route:'/settings/api/docs',permissions:['api.read'],dependencies:['api-keys']}),
module('api-playground','API Playground','Интерактивное выполнение запросов.',['Provider','Asset','Operation','JSON Editor','Copy JSON','Copy cURL','Execute','Response Viewer','Request History'],{route:'/settings/api/playground',permissions:['api.execute'],dependencies:['api-documentation']}),
module('webhooks','Webhooks','Исходящие события платформы.',['Endpoint Management','Signing Secret','Event Selection','Delivery History','Retry','Disable','Test Event'],{route:'/settings/webhooks',permissions:['webhooks.manage'],dependencies:['audit']}),
module('mcp','MCP','Доступ к функциям платформы через MCP.',['MCP Setup','Tools','Permissions','API Access','Connection Status','Audit Log'],{route:'/settings/mcp',permissions:['mcp.manage'],dependencies:['api-keys','permissions']})]},
{id:'settings-security',name:'Settings and Security',description:'Профиль, безопасность и управление данными.',modules:[
module('user-settings','User Settings','Личные настройки пользователя.',['Profile','Avatar','Language','Timezone','Theme','Notifications','Password','MFA','Sessions'],{route:'/settings/profile',permissions:['profile.manage']}),
module('agency-settings','Agency Settings','Общие настройки агентства.',['Company','Branding','Domain','Billing','Users','Permissions','Notifications','API','Integrations'],{route:'/settings',permissions:['agency.manage'],dependencies:['agency-profile']}),
module('security','Security','Политики безопасности.',['Password Policy','Leaked Password Protection','MFA Policy','Session Policy','Allowed Domains','IP Allowlist','Login Alerts','Security Events','API Security'],{route:'/settings/security',permissions:['security.manage'],dependencies:['authentication','audit']}),
module('data-governance','Data Governance','Политики хранения и приватности.',['Data Retention','Data Export','Data Deletion','Consent','Privacy Requests','Encryption','Backup','Restore','Data Residency'],{route:'/settings/data-governance',permissions:['data_governance.manage'],dependencies:['audit']})]},
{id:'support',name:'Support',description:'Документация, обращения и обратная связь.',modules:[
module('help-center','Help Center','База знаний.',['Documentation','Guides','Tutorials','FAQs','Search','Release Notes'],{route:'/help',permissions:['help.read']}),
module('support-tickets','Support Tickets','Обращения в поддержку.',['Create Ticket','Status','Priority','Messages','Attachments','Assignment','History'],{route:'/support',permissions:['support.use'],dependencies:['file-manager']}),
module('product-feedback','Product Feedback','Запросы функций и сообщения об ошибках.',['Bug Report','Feature Request','Voting','Roadmap','Satisfaction Score'],{route:'/feedback',permissions:['feedback.create']})]},
{id:'superadmin',name:'Superadmin',description:'Системное администрирование платформы.',modules:[
module('tenant-management','Tenant Management','Управление агентствами и клиентами.',['Agencies','Clients','Users','Status','Limits','Suspend','Restore','Impersonation'],{surface:'superadmin',route:'/superadmin/tenants',permissions:['superadmin.tenants']}),
module('subscription-administration','Subscription Administration','Администрирование тарифов.',['Plans','Prices','Trials','Subscriptions','Coupons','Limits','Entitlements'],{surface:'superadmin',route:'/superadmin/subscriptions',permissions:['superadmin.billing'],dependencies:['billing']}),
module('integration-administration','Integration Administration','Настройка каталога и провайдеров.',['Catalog','Provider Configuration','OAuth Settings','Lifecycle','Beta Flags','Credentials','Rate Limits'],{surface:'superadmin',route:'/superadmin/integrations',permissions:['superadmin.integrations'],dependencies:['integration-catalog']}),
module('jobs-administration','Jobs Administration','Управление очередями и workers.',['Sync Jobs','Export Jobs','Notification Jobs','Failed Jobs','Retries','Dead-Letter Queue','Worker Health'],{surface:'superadmin',route:'/superadmin/jobs',permissions:['superadmin.jobs'],dependencies:['sync-worker','export-worker']}),
module('feature-administration','Feature Administration','Управление feature flags.',['Feature Flags','Tenant Flags','Beta Programs','Rollout','Kill Switch'],{surface:'superadmin',route:'/superadmin/features',permissions:['superadmin.features'],dependencies:['feature-flags']}),
module('support-administration','Support Administration','Инструменты поддержки.',['Tickets','Tenant Diagnostics','Impersonation','User Activity','Audit Logs'],{surface:'superadmin',route:'/superadmin/support',permissions:['superadmin.support'],dependencies:['support-tickets','audit']}),
module('system-monitoring','System Monitoring','Мониторинг платформы.',['API Health','Database Health','Worker Health','OAuth Errors','Sync Errors','Storage','Performance','Security Events'],{surface:'superadmin',route:'/superadmin/monitoring',permissions:['superadmin.monitoring'],dependencies:['observability']})]},
{id:'infrastructure',name:'Infrastructure and Operations',description:'Эксплуатационный контур платформы.',modules:[
module('configuration','Configuration','Конфигурация окружений и секретов.',['Environment Variables','Secret Management','Provider Configuration','Feature Configuration','Runtime Validation'],{surface:'backend'}),
module('ci-cd','CI/CD','Проверки и доставка изменений.',['Typecheck','Lint','Unit Tests','Integration Tests','Production Build','Database Checks','Preview Deployment','Production Deployment','Rollback'],{surface:'backend',dependencies:['configuration']}),
module('observability','Observability','Логи, метрики и трассировка.',['Logs','Metrics','Traces','Error Tracking','Performance Monitoring','Alerts','Dashboards'],{surface:'backend',dependencies:['configuration']}),
module('database-operations','Database Operations','Операции с базой данных.',['Migrations','Seeds','Backups','Restore','RLS Tests','Performance Advisors','Security Advisors'],{surface:'backend',dependencies:['configuration']}),
module('job-infrastructure','Job Infrastructure','Очереди и исполнение фоновых задач.',['Queue','Scheduling','Locks','Retries','Idempotency','Priority','Dead-Letter Queue','Worker Scaling'],{surface:'backend',dependencies:['observability']}),
module('storage-infrastructure','Storage Infrastructure','Хранение файлов и экспортов.',['Logos','Files','Reports','Exports','Temporary Files','Signed URLs','Retention','Cleanup'],{surface:'backend',dependencies:['configuration']})]},
{id:'backend-services',name:'Backend Services',description:'Основные сервисные контуры.',modules:[
module('platform-core-service','Platform Core Service','Tenant, users, permissions, branding, billing и audit.',['Tenants','Users','Memberships','Permissions','Branding','Entitlements','Billing','Audit'],{status:'development',surface:'backend',dependencies:['platform-core']}),
module('integration-service','Integration Service','OAuth, credentials и account discovery.',['OAuth','API Keys','Credentials','Token Refresh','Account Discovery','Provider Catalog'],{status:'development',surface:'backend',dependencies:['connection-manager']}),
module('report-api','Report API','Безопасная выдача аналитики.',['Tenant Verification','Permissions','Metrics','Aggregations','Dashboard Data','Reports','KPIs','Roll-Ups','Views'],{status:'development',surface:'backend',dependencies:['multi-tenancy','raw-data-processing']}),
module('notification-worker','Notification Worker','Фоновая доставка уведомлений.',['Email','In-App','Slack','Telegram','Webhooks','Retries'],{surface:'backend',dependencies:['notification-channels','job-infrastructure']}),
module('ai-service','AI Service','Изолированный AI-контур.',['Provider Gateway','Prompt Templates','RAG','Tool Execution','Usage Metering','Safety Policies'],{surface:'backend',entitlements:['ai'],dependencies:['ai-governance']}),
module('search-indexer','Search Indexer','Индексирование сущностей платформы.',['Client Index','Dashboard Index','Report Index','Campaign Index','File Index','Incremental Updates'],{surface:'backend',dependencies:['global-search','job-infrastructure']})]}
];

export const allModules=moduleDomains.flatMap(domain=>domain.modules);
export const moduleById=new Map(allModules.map(item=>[item.id,item]));
export const moduleCounts={domains:moduleDomains.length,modules:allModules.length,submodules:allModules.reduce((sum,item)=>sum+item.submodules.length,0)};

export const modulesBySurface=(surface:ModuleSurface)=>allModules.filter(item=>item.surface===surface);
export const modulesByStatus=(status:ModuleStatus)=>allModules.filter(item=>item.status===status);
