export type ModuleDeliveryStatus='not_started'|'in_progress'|'complete'|'error';
export interface ModuleProgressRecord{status:ModuleDeliveryStatus;note?:string}
export const moduleDeliveryLabels:Record<ModuleDeliveryStatus,string>={not_started:'Не начат',in_progress:'В работе',complete:'Полностью готов',error:'Ошибка'};
export const moduleCompletionCriteria=['Завершён дизайн модуля и всех адаптивных состояний','Реализованы все заявленные подмодули','Созданы и подключены все внутренние страницы и маршруты','Работают формы, кнопки, фильтры и пользовательские действия','Подключены API, база данных и фоновые процессы','Применены permissions, entitlements и tenant isolation','Обработаны loading, empty, success и error states','Пройдены typecheck, тесты и production build'] as const;
const progress:Record<string,ModuleProgressRecord>={
 authentication:{status:'in_progress'},workspace:{status:'in_progress'},'multi-tenancy':{status:'in_progress'},permissions:{status:'in_progress'},audit:{status:'in_progress'},
 'agency-profile':{status:'complete',note:'Company, legal, contact, locale, hours, markup and default settings'},'users-teams':{status:'complete',note:'Email invitations, roles, status, teams and client assignments'},billing:{status:'complete',note:'Plans, subscription lifecycle, usage, limits and invoices'},'agency-onboarding':{status:'complete',note:'Guided checklist and persisted setup progress'},
 'client-directory':{status:'complete',note:'Search, status/group filters, summary, actions and responsive table'},'client-creation':{status:'complete',note:'Live creation form with tenant-scoped Clients API'},'client-profile':{status:'complete',note:'Live client business profile and editable context'},'client-users':{status:'complete',note:'Client roles and access list backed by Clients API'},'client-settings':{status:'complete',note:'Timezone, language, currency, retention and agency markup'},'client-groups':{status:'complete',note:'Group creation, filtering and client counts'},
 'integration-catalog':{status:'complete',note:'90 connectors, exact branding, filters and lifecycle-aware connection actions'},'connection-manager':{status:'complete',note:'OAuth/manual credentials, account discovery, sync, pause, resume, disconnect and delete'},'agency-connections':{status:'complete',note:'Shared grants, client attachments, expiration state and credential revocation'},'data-source-management':{status:'complete',note:'Client-scoped source status, manual sync, backfill controls and lifecycle actions'},'integration-schema':{status:'complete',note:'Provider entity, dimension and metric registry for implemented adapters'},'sync-health':{status:'complete',note:'Queue, attempts, freshness, errors and run history'},
 'sync-dispatcher':{status:'complete',note:'Atomic queue claims, deduplication, priorities, scheduled reconciliation and safe retries'},'sync-worker':{status:'complete',note:'Tenant-safe processing, chunked idempotent upserts, quality telemetry and classified retries'},'provider-adapters':{status:'complete',note:'Meta, TikTok, Google Ads, GA4 and Search Console adapters with normalized contracts'},'raw-data-processing':{status:'complete',note:'Schema validation, tenant checks, duplicate removal, quality thresholds and normalized metric facts'},
 campaigns:{status:'complete',note:'Live multi-platform campaign analytics with filters, period comparison, pagination, export and derived metrics'},'funnel-analytics':{status:'complete',note:'Impression-to-sale funnel, stage conversion, trend and unit economics backed by Report API'},
 'dashboard-directory':{status:'complete',note:'Live dashboard catalog with create, rename, duplicate, archive, delete, reorder and default state'},'dashboard-builder':{status:'complete',note:'Responsive 12-column editor with sections, drag, resize and persisted layouts'},'widget-builder':{status:'complete',note:'Stat, KPI, charts, table, funnel, progress and text widgets'},'widget-configuration':{status:'complete',note:'Metric, source, aggregation, breakdown, comparison, sorting, limits, formatting and color'},'dashboard-filters':{status:'complete',note:'Global date, integration, account, campaign, device and region filters plus widget filters'},
 configuration:{status:'in_progress'},'ci-cd':{status:'in_progress'},observability:{status:'in_progress'},'database-operations':{status:'in_progress'},'job-infrastructure':{status:'in_progress'},
 'platform-core-service':{status:'complete',note:'Tenant workspace, users, memberships, permissions, branding, entitlements, billing usage and audit API'},'integration-service':{status:'complete',note:'OAuth and manual credentials, encrypted vault, refresh, discovery, provider catalog and operational health'},'report-api':{status:'complete',note:'Tenant-safe raw metrics, advertising analytics, aggregations, dashboard data, report CRUD, KPI and roll-up APIs'},'notification-worker':{status:'complete',note:'Email, in-app, Slack, Telegram and signed webhook delivery with idempotent retries'},'ai-service':{status:'complete',note:'Entitlement-gated provider gateway, prompt templates, tenant RAG, allowlisted tools, safety and usage metering'},'search-indexer':{status:'complete',note:'Tenant search documents, incremental jobs, rebuilds and indexes for clients, dashboards, reports, campaigns and files'},
};
export function getModuleDelivery(moduleId:string):ModuleProgressRecord{return progress[moduleId]??{status:'not_started'}}
export function getModuleDeliveryStatus(moduleId:string):ModuleDeliveryStatus{return getModuleDelivery(moduleId).status}
