import{useEffect,useMemo,useState}from'react';
import{useMutation,useQuery}from'@tanstack/react-query';
import{useNavigate,useParams}from'@tanstack/react-router';
import{ArrowDown,ArrowLeft,ArrowUp,Eye,FileText,Image,LayoutTemplate,Plus,Save,Trash2,Type,Workflow}from'lucide-react';
import{Button,Card}from'@imds/ui';
import{canAccess,permissions}from'@imds/permissions';
import{useAuth}from'../../app/AuthProvider';
import{getReportDocument,listReportWidgets,saveReportDocument,type ReportBlock,type ReportBlockType,type ReportDocument}from'../../report-builder-api';
import{ForbiddenPage}from'../ForbiddenPage';
import'./report-builder.css';

const labels:Record<ReportBlockType,string>={section:'Секция',text:'Текст',image:'Изображение',widget:'Виджет',page_break:'Разрыв страницы'};
const icons:Record<ReportBlockType,typeof Type>={section:LayoutTemplate,text:Type,image:Image,widget:Workflow,page_break:FileText};
const newBlock=(type:ReportBlockType):ReportBlock=>({type,title:labels[type],content:type==='text'?{text:'Новый текстовый блок'}:type==='image'?{url:'',alt:''}:type==='widget'?{widgetId:''}:{},settings:{}});

export function ReportBuilderPage(){const{workspace,session}=useAuth();const{clientId,reportId}=useParams({strict:false})as{clientId:string;reportId:string};if(!workspace)return <Card className="loading-card">Загрузка конструктора…</Card>;const agency=workspace.activeAgency;if(!agency||!canAccess(agency,permissions.reportsRead))return <ForbiddenPage/>;return <Builder agencyId={agency.id} clientId={clientId} reportId={reportId} canManage={canAccess(agency,permissions.reportsManage)} session={session} mode={workspace.mode}/>}

function Builder({agencyId,clientId,reportId,canManage,session,mode}:{agencyId:string;clientId:string;reportId:string;canManage:boolean;session:ReturnType<typeof useAuth>['session'];mode:'supabase'}){
 const navigate=useNavigate();const documentQuery=useQuery({queryKey:['report-document',agencyId,reportId],queryFn:()=>getReportDocument(reportId,agencyId,session,mode)});const widgetsQuery=useQuery({queryKey:['report-widgets',agencyId,reportId],queryFn:()=>listReportWidgets(reportId,agencyId,session,mode)});const[document,setDocument]=useState<ReportDocument|null>(null);const[selectedPage,setSelectedPage]=useState(0);const[preview,setPreview]=useState(false);const[dirty,setDirty]=useState(false);
 useEffect(()=>{if(documentQuery.data){setDocument(documentQuery.data);setDirty(false)}},[documentQuery.data]);
 const saveMutation=useMutation({mutationFn:()=>saveReportDocument(document!,session,mode),onSuccess:saved=>{setDocument(saved);setDirty(false)}});
 const page=document?.pages[selectedPage];const update=(next:ReportDocument)=>{setDocument(next);setDirty(true)};
 const updatePage=(patch:Partial<NonNullable<typeof page>>)=>{if(!document||!page)return;const pages=document.pages.map((item,index)=>index===selectedPage?{...item,...patch}:item);update({...document,pages})};
 const addPage=()=>{if(!document)return;update({...document,pages:[...document.pages,{title:`Страница ${document.pages.length+1}`,settings:{},blocks:[]}]});setSelectedPage(document.pages.length)};
 const removePage=()=>{if(!document||document.pages.length===1)return;const pages=document.pages.filter((_,index)=>index!==selectedPage);update({...document,pages});setSelectedPage(Math.max(0,selectedPage-1))};
 const addBlock=(type:ReportBlockType)=>{if(!page)return;updatePage({blocks:[...page.blocks,newBlock(type)]})};
 const patchBlock=(index:number,patch:Partial<ReportBlock>)=>{if(!page)return;updatePage({blocks:page.blocks.map((block,i)=>i===index?{...block,...patch}:block)})};
 const moveBlock=(index:number,delta:number)=>{if(!page)return;const target=index+delta;if(target<0||target>=page.blocks.length)return;const blocks=[...page.blocks];[blocks[index],blocks[target]]=[blocks[target],blocks[index]];updatePage({blocks})};
 const deleteBlock=(index:number)=>{if(!page)return;updatePage({blocks:page.blocks.filter((_,i)=>i!==index)})};
 const status=useMemo(()=>saveMutation.isPending?'Сохранение…':saveMutation.error?'Ошибка сохранения':dirty?'Есть несохранённые изменения':'Сохранено',[dirty,saveMutation.error,saveMutation.isPending]);
 if(documentQuery.isLoading||!document)return <Card className="loading-card">Загрузка документа…</Card>;if(documentQuery.error)return <Card className="loading-card">Не удалось загрузить отчёт: {documentQuery.error.message}</Card>;
 return <div className={preview?'report-builder preview-mode':'report-builder'}>
  <header className="builder-header"><div className="builder-header-left"><Button variant="secondary" onClick={()=>navigate({to:'/reports'})}><ArrowLeft size={16}/> Каталог</Button><div><input className="builder-title" value={document.name} disabled={!canManage} onChange={event=>update({...document,name:event.target.value})}/><span>{status}</span></div></div><div className="builder-actions"><Button variant="secondary" onClick={()=>setPreview(value=>!value)}><Eye size={16}/> {preview?'Редактор':'Предпросмотр'}</Button>{canManage&&<Button disabled={!dirty||saveMutation.isPending} onClick={()=>saveMutation.mutate()}><Save size={16}/> Сохранить</Button>}</div></header>
  <div className="builder-layout">
   {!preview&&<aside className="builder-sidebar"><div className="sidebar-heading"><strong>Страницы</strong>{canManage&&<button onClick={addPage}><Plus size={16}/></button>}</div>{document.pages.map((item,index)=><button key={item.id??index} className={index===selectedPage?'page-tab active':'page-tab'} onClick={()=>setSelectedPage(index)}><span>{index+1}</span><div><strong>{item.title}</strong><small>{item.blocks.length} блоков</small></div></button>)}{canManage&&<Button variant="secondary" disabled={document.pages.length===1} onClick={removePage}><Trash2 size={15}/> Удалить страницу</Button>}</aside>}
   <main className="builder-canvas"><section className="paper-page"><div className="paper-header">{document.branding.logoUrl?<img src={String(document.branding.logoUrl)} alt="Логотип"/>:<strong>{document.name}</strong>}<span>{clientId}</span></div>{!preview&&<input className="page-title-input" value={page?.title??''} onChange={event=>updatePage({title:event.target.value})}/>}<div className="report-blocks">{page?.blocks.map((block,index)=><BlockEditor key={block.id??`${block.type}-${index}`} block={block} index={index} canManage={canManage&&!preview} widgetOptions={widgetsQuery.data??[]} onPatch={patch=>patchBlock(index,patch)} onMove={moveBlock} onDelete={deleteBlock}/>)}</div>{page?.blocks.length===0&&<div className="empty-page">Добавьте первый блок на страницу.</div>}<div className="paper-footer">Страница {selectedPage+1} из {document.pages.length}</div></section></main>
   {!preview&&canManage&&<aside className="block-palette"><strong>Добавить блок</strong>{(['section','text','image','widget','page_break'] as ReportBlockType[]).map(type=>{const Icon=icons[type];return <button key={type} onClick={()=>addBlock(type)}><Icon size={18}/><span>{labels[type]}</span></button>})}<label>Цвет бренда<input type="color" value={String(document.branding.primaryColor??'#2563eb')} onChange={event=>update({...document,branding:{...document.branding,primaryColor:event.target.value}})}/></label><label>Описание<textarea value={document.description} onChange={event=>update({...document,description:event.target.value})}/></label></aside>}
  </div>
 </div>;
}

function BlockEditor({block,index,canManage,widgetOptions,onPatch,onMove,onDelete}:{block:ReportBlock;index:number;canManage:boolean;widgetOptions:{id:string;title:string;dashboardName:string}[];onPatch:(patch:Partial<ReportBlock>)=>void;onMove:(index:number,delta:number)=>void;onDelete:(index:number)=>void}){return <article className={`report-block block-${block.type}`}><div className="block-toolbar"><span>{labels[block.type]}</span>{canManage&&<div><button onClick={()=>onMove(index,-1)}><ArrowUp size={14}/></button><button onClick={()=>onMove(index,1)}><ArrowDown size={14}/></button><button onClick={()=>onDelete(index)}><Trash2 size={14}/></button></div>}</div>{block.type==='section'&&<><input className="section-title" value={block.title} disabled={!canManage} onChange={event=>onPatch({title:event.target.value})}/><input value={String(block.content.subtitle??'')} disabled={!canManage} placeholder="Подзаголовок" onChange={event=>onPatch({content:{...block.content,subtitle:event.target.value}})}/></>}{block.type==='text'&&<textarea value={String(block.content.text??'')} disabled={!canManage} onChange={event=>onPatch({content:{...block.content,text:event.target.value}})}/>} {block.type==='image'&&<><input value={String(block.content.url??'')} disabled={!canManage} placeholder="https://…" onChange={event=>onPatch({content:{...block.content,url:event.target.value}})}/>{block.content.url?<img src={String(block.content.url)} alt={String(block.content.alt??'')}/>:<div className="image-placeholder"><Image size={28}/> URL изображения</div>}</>}{block.type==='widget'&&<><select value={String(block.content.widgetId??'')} disabled={!canManage} onChange={event=>onPatch({content:{...block.content,widgetId:event.target.value}})}><option value="">Выберите виджет</option>{widgetOptions.map(widget=><option key={widget.id} value={widget.id}>{widget.dashboardName} — {widget.title}</option>)}</select><div className="widget-preview"><Workflow size={28}/><strong>{widgetOptions.find(item=>item.id===block.content.widgetId)?.title??'Виджет не выбран'}</strong><span>Данные подставляются при генерации отчёта</span></div></>}{block.type==='page_break'&&<div className="page-break-line"><span>Разрыв страницы</span></div>}</article>}
