import {Injectable,Logger,OnModuleDestroy,OnModuleInit} from '@nestjs/common';
import {Db} from './db.js';
import {config} from './config.js';
type IndexJob={id:string;agency_id:string;client_id:string|null;entity_type:string;entity_id:string;operation:'upsert'|'delete'|'rebuild';payload:Record<string,unknown>;attempts:number;max_attempts:number};
type SearchDoc={agencyId:string;clientId:string|null;entityType:string;entityId:string;title:string;content:string;url:string|null;metadata:Record<string,unknown>};
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
@Injectable()
export class IndexerService implements OnModuleInit,OnModuleDestroy{
  private readonly logger=new Logger(IndexerService.name);private controller=new AbortController();private loop?:Promise<void>;
  constructor(private readonly db:Db){}
  onModuleInit(){if(config.INDEXER_ENABLED)this.loop=this.run(this.controller.signal)}
  async onModuleDestroy(){this.controller.abort();await this.loop?.catch(()=>undefined)}
  async enqueue(input:{agencyId:string;clientId?:string|null;entityType:string;entityId:string;operation?:'upsert'|'delete'|'rebuild';payload?:Record<string,unknown>}){const result=await this.db.query(`insert into public.search_index_jobs(agency_id,client_id,entity_type,entity_id,operation,payload,dedupe_key) values($1,$2,$3,$4,$5,$6,$7) on conflict(dedupe_key) where dedupe_key is not null and state in ('queued','running') do update set payload=excluded.payload,run_after=now(),updated_at=now() returning *`,[input.agencyId,input.clientId??null,input.entityType,input.entityId,input.operation??'upsert',input.payload??{},`${input.operation??'upsert'}:${input.agencyId}:${input.entityType}:${input.entityId}`]);return result.rows[0]}
  private async claim(){return this.db.transaction(async client=>{const selected=await client.query<{id:string}>(`select id from public.search_index_jobs where state='queued' and run_after<=now() and attempts<max_attempts order by priority,created_at for update skip locked limit 1`);if(!selected.rows[0])return null;const result=await client.query<IndexJob>(`update public.search_index_jobs set state='running',attempts=attempts+1,locked_at=now(),locked_by=$2,updated_at=now() where id=$1 returning *`,[selected.rows[0].id,config.WORKER_ID]);return result.rows[0]})}
  private async upsert(doc:SearchDoc){await this.db.query(`insert into public.search_documents(agency_id,client_id,entity_type,entity_id,title,content,url,metadata,indexed_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,now(),now()) on conflict(agency_id,entity_type,entity_id) do update set client_id=excluded.client_id,title=excluded.title,content=excluded.content,url=excluded.url,metadata=excluded.metadata,indexed_at=now(),updated_at=now()`,[doc.agencyId,doc.clientId,doc.entityType,doc.entityId,doc.title,doc.content,doc.url,doc.metadata])}
  private async delete(agencyId:string,entityType:string,entityId:string){await this.db.query(`delete from public.search_documents where agency_id=$1 and entity_type=$2 and entity_id=$3`,[agencyId,entityType,entityId])}
  private async fromPayload(job:IndexJob){const payload=job.payload||{};await this.upsert({agencyId:job.agency_id,clientId:job.client_id,entityType:job.entity_type,entityId:job.entity_id,title:String(payload.title||job.entity_id),content:String(payload.content||''),url:payload.url?String(payload.url):null,metadata:(payload.metadata&&typeof payload.metadata==='object'?payload.metadata:{}) as Record<string,unknown>})}
  private async rebuildAgency(agencyId:string){
    const documents:SearchDoc[]=[];
    const clients=await this.db.query<any>(`select id,company,url,country,language,status from public.clients where agency_id=$1`,[agencyId]);for(const row of clients.rows)documents.push({agencyId,clientId:row.id,entityType:'client',entityId:row.id,title:row.company,content:[row.url,row.country,row.language,row.status].filter(Boolean).join(' '),url:`/client/${row.id}`,metadata:{status:row.status}});
    const dashboards=await this.db.query<any>(`select id,client_id,name,settings from public.dashboards where agency_id=$1`,[agencyId]);for(const row of dashboards.rows)documents.push({agencyId,clientId:row.client_id,entityType:'dashboard',entityId:row.id,title:row.name,content:JSON.stringify(row.settings||{}),url:`/client/${row.client_id}/dashboards/${row.id}`,metadata:{}});
    const reportsExist=await this.db.query<{exists:boolean}>(`select to_regclass('public.reports') is not null exists`);if(reportsExist.rows[0]?.exists){const reports=await this.db.query<any>(`select id,client_id,name,description,status from public.reports where agency_id=$1`,[agencyId]);for(const row of reports.rows)documents.push({agencyId,clientId:row.client_id,entityType:'report',entityId:row.id,title:row.name,content:`${row.description||''} ${row.status||''}`,url:`/reports/${row.id}`,metadata:{status:row.status}})}
    const campaigns=await this.db.query<any>(`select client_id,entity_id,max(coalesce(entity_name,entity_id)) entity_name,jsonb_object_agg(metric_key,total) metrics from (select client_id,entity_id,entity_name,metric_key,sum(value) total from public.marketing_daily_metrics where agency_id=$1 and entity_type='campaign' and metric_date>=current_date-90 group by client_id,entity_id,entity_name,metric_key) x group by client_id,entity_id`,[agencyId]);for(const row of campaigns.rows)documents.push({agencyId,clientId:row.client_id,entityType:'campaign',entityId:row.entity_id,title:row.entity_name,content:JSON.stringify(row.metrics||{}),url:`/client/${row.client_id}/campaigns`,metadata:{metrics:row.metrics}});
    const storageExists=await this.db.query<{exists:boolean}>(`select to_regclass('storage.objects') is not null exists`);if(storageExists.rows[0]?.exists){const files=await this.db.query<any>(`select id::text,name,metadata from storage.objects where name like $1 order by updated_at desc limit 2000`,[`${agencyId}/%`]);for(const row of files.rows)documents.push({agencyId,clientId:null,entityType:'file',entityId:row.id,title:String(row.name).split('/').at(-1)||row.name,content:row.name,url:null,metadata:row.metadata||{}})}
    await this.db.query(`delete from public.search_documents where agency_id=$1 and entity_type in ('client','dashboard','report','campaign','file')`,[agencyId]);for(const doc of documents)await this.upsert(doc);return documents.length;
  }
  private async process(job:IndexJob){if(job.operation==='delete')return this.delete(job.agency_id,job.entity_type,job.entity_id);if(job.operation==='rebuild'||job.entity_type==='agency')return this.rebuildAgency(job.agency_id);return this.fromPayload(job)}
  private async complete(jobId:string){await this.db.query(`update public.search_index_jobs set state='succeeded',locked_at=null,locked_by=null,last_error=null,finished_at=now(),updated_at=now() where id=$1 and locked_by=$2`,[jobId,config.WORKER_ID])}
  private async fail(job:IndexJob,error:unknown){const failure={name:error instanceof Error?error.name:'Error',message:error instanceof Error?error.message:String(error)};const exhausted=job.attempts>=job.max_attempts;await this.db.query(`update public.search_index_jobs set state=case when $3 then 'failed' else 'queued' end,run_after=case when $3 then run_after else now()+make_interval(secs=>least(3600,60*power(2,greatest(attempts-1,0))::int)) end,locked_at=null,locked_by=null,last_error=$2,finished_at=case when $3 then now() else null end,updated_at=now() where id=$1`,[job.id,failure,exhausted])}
  async runOnce(){const job=await this.claim();if(!job)return false;try{await this.process(job);await this.complete(job.id)}catch(error){await this.fail(job,error);this.logger.error(`Index job ${job.id} failed`,error instanceof Error?error.stack:String(error))}return true}
  private async run(signal:AbortSignal){while(!signal.aborted){const worked=await this.runOnce();if(!worked)await sleep(config.POLL_INTERVAL_MS)}}
  async search(agencyId:string,query:string,clientId:string|null,limit:number){const result=await this.db.query(`select id,agency_id,client_id,entity_type,entity_id,title,left(content,500) snippet,url,metadata,ts_rank(search_vector,websearch_to_tsquery('simple',$3)) rank,updated_at from public.search_documents where agency_id=$1 and ($2::uuid is null or client_id is null or client_id=$2) and search_vector @@ websearch_to_tsquery('simple',$3) order by rank desc,updated_at desc limit $4`,[agencyId,clientId,query,Math.min(Math.max(limit,1),100)]);return{items:result.rows}}
}
