import {Badge,Button,Card} from '@imds/ui';
import {canAccess,permissions} from '@imds/permissions';
import {useAuth} from '../app/AuthProvider';
import {ForbiddenPage} from './ForbiddenPage';

export function ClientsPage(){const{workspace,refresh}=useAuth();if(!workspace)return <Card className="loading-card">Loading workspace…</Card>;if(!canAccess(workspace.activeAgency,permissions.clientsRead))return <ForbiddenPage/>;const sources=workspace.clients.reduce((sum,client)=>sum+client.connectedSources,0);const canManage=canAccess(workspace.activeAgency,permissions.clientsManage);return <>
  <section className="page-heading"><div><h2>Clients</h2><p>Manage clients, access and connected marketing data.</p></div><div className="heading-actions"><Button variant="secondary" onClick={()=>void refresh()}>Refresh</Button><Button variant="secondary">Add Filter</Button>{canManage&&<Button>Add Client</Button>}</div></section>
  <section className="stats-grid"><Card><span>Total clients</span><strong>{workspace.clients.length}</strong><small>Across {workspace.agencies.length} agency workspace</small></Card><Card><span>Connected sources</span><strong>{sources}</strong><small>Meta Ads and TikTok Ads</small></Card><Card><span>Workspace mode</span><strong>{workspace.mode==='demo'?'Demo':'Live'}</strong><small>{workspace.mode==='demo'?'Configure Supabase to enable live data':'Supabase connected'}</small></Card></section>
  <Card className="table-card"><div className="table-toolbar"><div><h2>Clients</h2><span>Showing {workspace.clients.length} of {workspace.clients.length} Rows</span></div><input aria-label="Search clients" placeholder="Search clients"/></div><div className="table-wrap"><table><thead><tr><th/><th>Client</th><th>Domain</th><th>Status</th><th>Data Sources</th><th>Created</th><th/></tr></thead><tbody>{workspace.clients.map(client=><tr key={client.id}><td><input type="checkbox" aria-label={`Select ${client.company}`}/></td><td><div className="client-cell"><div className="client-logo" style={{background:client.brandColor}}>{client.company.slice(0,2).toUpperCase()}</div><div><strong>{client.company}</strong><span>{client.id}</span></div></div></td><td>{client.url??'—'}</td><td><Badge tone={client.status==='active'?'success':'warning'}>{client.status}</Badge></td><td>{client.connectedSources}</td><td>{new Date(client.createdAt).toLocaleDateString('ru-RU')}</td><td><button className="icon-button">⋯</button></td></tr>)}</tbody><tfoot><tr><td colSpan={4}>TOTALS</td><td>{sources}</td><td colSpan={2}>{workspace.clients.length} clients</td></tr></tfoot></table></div></Card>
</>}
