import {Badge,Button,Card} from '@imds/ui';
import {canAccess,permissions} from '@imds/permissions';
import {useAuth} from '../app/AuthProvider';
import {useI18n} from '../i18n/I18nProvider';
import {ForbiddenPage} from './ForbiddenPage';

export function ClientsPage(){const{workspace,refresh}=useAuth();const{t,locale}=useI18n();if(!workspace)return <Card className="loading-card">{t('common.loadingWorkspace')}</Card>;if(!canAccess(workspace.activeAgency,permissions.clientsRead))return <ForbiddenPage/>;const sources=workspace.clients.reduce((sum,client)=>sum+client.connectedSources,0);const canManage=canAccess(workspace.activeAgency,permissions.clientsManage);return <>
  <section className="page-heading"><div><h2>{t('clients.title')}</h2><p>{t('clients.description')}</p></div><div className="heading-actions"><Button variant="secondary" onClick={()=>void refresh()}>{t('common.refresh')}</Button><Button variant="secondary">{t('common.addFilter')}</Button>{canManage&&<Button>{t('common.addClient')}</Button>}</div></section>
  <section className="stats-grid"><Card><span>{t('clients.totalClients')}</span><strong>{workspace.clients.length}</strong><small>{t('clients.acrossWorkspaces',{count:workspace.agencies.length})}</small></Card><Card><span>{t('clients.connectedSources')}</span><strong>{sources}</strong><small>{t('clients.connectedSourceHint')}</small></Card><Card><span>{t('clients.workspaceMode')}</span><strong>{workspace.mode==='demo'?t('clients.demo'):t('clients.live')}</strong><small>{workspace.mode==='demo'?t('clients.configureSupabase'):t('clients.supabaseConnected')}</small></Card></section>
  <Card className="table-card"><div className="table-toolbar"><div><h2>{t('clients.title')}</h2><span>{t('clients.showingRows',{shown:workspace.clients.length,total:workspace.clients.length})}</span></div><input aria-label={t('clients.search')} placeholder={t('clients.search')}/></div><div className="table-wrap"><table><thead><tr><th/><th>{t('clients.client')}</th><th>{t('clients.domain')}</th><th>{t('clients.status')}</th><th>{t('clients.dataSources')}</th><th>{t('clients.created')}</th><th/></tr></thead><tbody>{workspace.clients.map(client=><tr key={client.id}><td><input type="checkbox" aria-label={t('clients.selectClient',{name:client.company})}/></td><td><div className="client-cell"><div className="client-logo" style={{background:client.brandColor}}>{client.company.slice(0,2).toUpperCase()}</div><div><strong>{client.company}</strong><span>{client.id}</span></div></div></td><td>{client.url??'—'}</td><td><Badge tone={client.status==='active'?'success':'warning'}>{t(`clients.statuses.${client.status}`)}</Badge></td><td>{client.connectedSources}</td><td>{new Date(client.createdAt).toLocaleDateString(locale)}</td><td><button className="icon-button">⋯</button></td></tr>)}</tbody><tfoot><tr><td colSpan={4}>{t('clients.totals')}</td><td>{sources}</td><td colSpan={2}>{t('clients.clientsCount',{count:workspace.clients.length})}</td></tr></tfoot></table></div></Card>
</>}
