import{useMemo,useState}from'react';
import{allModules,moduleCounts,moduleDomains}from'../modules/catalog';
import type{ModuleStatus,ModuleSurface}from'../modules/types';

const statusLabels:Record<ModuleStatus,string>={planned:'План',prototype:'Прототип',development:'Разработка',beta:'Beta',stable:'Стабильно',deprecated:'Устаревает',disabled:'Отключено'};
const surfaceLabels:Record<ModuleSurface,string>={workspace:'Workspace','client-portal':'Client Portal',superadmin:'Superadmin',backend:'Backend',shared:'Shared'};

export function ModuleCatalogPage(){
 const[query,setQuery]=useState('');
 const[status,setStatus]=useState<'all'|ModuleStatus>('all');
 const[surface,setSurface]=useState<'all'|ModuleSurface>('all');
 const visible=useMemo(()=>moduleDomains.map(domain=>({...domain,modules:domain.modules.filter(item=>{
  const text=`${item.name} ${item.description} ${item.submodules.join(' ')} ${item.route??''}`.toLowerCase();
  return(!query||text.includes(query.toLowerCase()))&&(status==='all'||item.status===status)&&(surface==='all'||item.surface===surface);
 })})).filter(domain=>domain.modules.length),[query,status,surface]);
 return <div className="module-catalog-page">
  <style>{`.module-catalog-page{display:flex;flex-direction:column;gap:18px}.module-catalog-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.module-catalog-head h2{margin:0 0 6px;font-size:26px}.module-catalog-head p{margin:0;color:#667085}.module-stats{display:grid;grid-template-columns:repeat(3,minmax(120px,1fr));gap:10px}.module-stat{background:#fff;border:1px solid #e4e7ec;border-radius:10px;padding:14px}.module-stat span{font-size:11px;color:#667085;text-transform:uppercase}.module-stat strong{display:block;font-size:24px;margin-top:4px}.module-toolbar{display:grid;grid-template-columns:minmax(260px,1fr) 180px 180px;gap:10px;background:#fff;border:1px solid #e4e7ec;border-radius:10px;padding:12px}.module-toolbar input,.module-toolbar select{border:1px solid #d0d5dd;border-radius:8px;padding:10px 12px;background:#fff}.module-domain{display:flex;flex-direction:column;gap:10px}.module-domain>header h3{margin:0}.module-domain>header p{margin:3px 0 0;color:#667085}.module-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.module-card{background:#fff;border:1px solid #e4e7ec;border-radius:10px;padding:15px;display:flex;flex-direction:column;gap:12px}.module-card-top{display:flex;justify-content:space-between;gap:12px}.module-card h4{margin:0;font-size:15px}.module-card p{margin:4px 0 0;color:#667085;font-size:12px}.module-badges{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.module-badge{font-size:9px;font-weight:700;padding:4px 6px;border-radius:999px;background:#f2f4f7;color:#475467;white-space:nowrap}.module-badge.status-development{background:#eaf3ff;color:#005fcc}.module-badge.status-stable{background:#eaf8ef;color:#067647}.module-badge.status-beta{background:#fff4e5;color:#b54708}.module-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:11px}.module-meta div{background:#f8fafc;border-radius:7px;padding:8px}.module-meta span{display:block;color:#98a2b3;margin-bottom:3px}.module-submodules{display:flex;gap:6px;flex-wrap:wrap}.module-submodule{font-size:10px;padding:5px 7px;background:#f2f4f7;border-radius:6px}.module-empty{padding:40px;text-align:center;background:#fff;border:1px solid #e4e7ec;border-radius:10px;color:#667085}@media(max-width:1100px){.module-grid{grid-template-columns:1fr}.module-toolbar{grid-template-columns:1fr}.module-catalog-head{flex-direction:column}}`}</style>
  <section className="module-catalog-head"><div><h2>Архитектура модулей</h2><p>Единый реестр продукта: поверхности, статусы, маршруты, зависимости и подмодули.</p></div><div className="module-stats"><div className="module-stat"><span>Домены</span><strong>{moduleCounts.domains}</strong></div><div className="module-stat"><span>Модули</span><strong>{moduleCounts.modules}</strong></div><div className="module-stat"><span>Подмодули</span><strong>{moduleCounts.submodules}</strong></div></div></section>
  <section className="module-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Поиск модуля или подмодуля…"/><select value={surface} onChange={event=>setSurface(event.target.value as 'all'|ModuleSurface)}><option value="all">Все поверхности</option>{Object.entries(surfaceLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value as 'all'|ModuleStatus)}><option value="all">Все статусы</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></section>
  {visible.length?visible.map(domain=><section className="module-domain" key={domain.id}><header><h3>{domain.name}</h3><p>{domain.description}</p></header><div className="module-grid">{domain.modules.map(item=><article className="module-card" key={item.id}><div className="module-card-top"><div><h4>{item.name}</h4><p>{item.description}</p></div><div className="module-badges"><span className={`module-badge status-${item.status}`}>{statusLabels[item.status]}</span><span className="module-badge">{surfaceLabels[item.surface]}</span></div></div><div className="module-meta"><div><span>Маршрут</span>{item.route??'Сервисный модуль'}</div><div><span>Зависимости</span>{item.dependencies.length?item.dependencies.join(', '):'Нет'}</div><div><span>Permissions</span>{item.permissions.length?item.permissions.join(', '):'Не назначены'}</div><div><span>Entitlements</span>{item.entitlements.length?item.entitlements.join(', '):'Не требуются'}</div></div><div className="module-submodules">{item.submodules.map(submodule=><span className="module-submodule" key={submodule}>{submodule}</span>)}</div></article>)}</div></section>):<div className="module-empty">По выбранным фильтрам ничего не найдено. Всего в реестре: {allModules.length} модулей.</div>}
 </div>;
}
