export type AgencyRole='admin'|'staff'|'client';
export type WorkspaceTheme='system'|'light'|'dark';
export interface WorkspaceAgency{id:string;name:string;slug:string;role:AgencyRole;permissions:string[];branding:{primaryColor:string;logoUrl:string|null};plan?:string;trialEndsAt?:string|null}
export interface WorkspaceClient{id:string;company:string;url:string|null;status:'active'|'paused'|'archived';createdAt:string;logoUrl:string|null;brandColor:string;connectedSources:number}
export interface WorkspaceEntitlements{plan:string;trialEndsAt:string|null;entitlements:Record<string,boolean>;limits:Record<string,number>}
export interface WorkspaceFeatureFlag{enabled:boolean;config:Record<string,unknown>;description:string}
export interface WorkspacePreferences{language:string;timezone:string;theme:WorkspaceTheme;settings:Record<string,unknown>}
export interface WorkspaceProductContext{id:string;name:string;surface:string;route:string}
export interface WorkspaceRecentItem{id:number;clientId:string|null;itemType:string;itemId:string;title:string;route:string;visitedAt:string}
export interface WorkspaceBootstrap{currentUser:{id:string;email:string;name:string;avatarUrl:string|null};agencies:WorkspaceAgency[];activeAgency:WorkspaceAgency|null;clients:WorkspaceClient[];activeClientId:string|null;productContext:WorkspaceProductContext;entitlements:WorkspaceEntitlements;featureFlags:Record<string,WorkspaceFeatureFlag>;preferences:WorkspacePreferences;recentItems:WorkspaceRecentItem[];mode:'supabase'}
