export type AgencyRole='admin'|'staff'|'client';
export type WorkspaceTheme='system'|'light'|'dark';
export interface WorkspaceAgency{id:string;name:string;slug:string;role:AgencyRole;permissions:string[];branding:{primaryColor:string;logoUrl:string|null};plan?:string;trialEndsAt?:string|null}
export interface WorkspaceClient{id:string;company:string;url:string|null;status:'active'|'paused'|'archived';createdAt:string;logoUrl:string|null;brandColor:string;connectedSources:number}
export interface WorkspaceEntitlements{plan:string;trialEndsAt:string|null;entitlements:Record<string,boolean>;limits:Record<string,number>}
export interface WorkspaceFeatureFlag{enabled:boolean;config:Record<string,unknown>;description:string}
export interface WorkspacePreferences{language:string;timezone:string;theme:WorkspaceTheme;settings:Record<string,unknown>}
export interface WorkspaceProductContext{id:string;name:string;surface:string;route:string}
export interface WorkspaceRecentItem{id:number;clientId:string|null;itemType:string;itemId:string;title:string;route:string;visitedAt:string}
export interface WorkspaceBootstrap{currentUser:{id:string;email:string;name:string;avatarUrl:string|null};agencies:WorkspaceAgency[];activeAgency:WorkspaceAgency|null;clients:WorkspaceClient[];activeClientId:string|null;productContext:WorkspaceProductContext;entitlements:WorkspaceEntitlements;featureFlags:Record<string,WorkspaceFeatureFlag>;preferences:WorkspacePreferences;recentItems:WorkspaceRecentItem[];mode:'supabase'|'demo'}
const agency:WorkspaceAgency={id:'demo-agency',name:'IMDS Agency',slug:'imds',role:'admin',permissions:['*'],branding:{primaryColor:'#0072EE',logoUrl:null},plan:'trial',trialEndsAt:null};
const demo:WorkspaceBootstrap={currentUser:{id:'demo-user',email:'admin@imds.tech',name:'Имомали Худайкулов',avatarUrl:null},agencies:[agency],activeAgency:agency,clients:[{id:'amanat-med',company:'Amanat Med',url:'amanatmed.kz',status:'active',createdAt:'2026-08-01',logoUrl:null,brandColor:'#0072EE',connectedSources:2},{id:'demo-clinic',company:'Demo Clinic',url:'demo-clinic.kz',status:'paused',createdAt:'2026-08-03',logoUrl:null,brandColor:'#7C3AED',connectedSources:0}],activeClientId:'amanat-med',productContext:{id:'marketing',name:'IMDS Marketing',surface:'workspace',route:'/'},entitlements:{plan:'trial',trialEndsAt:null,entitlements:{clients:true,integrations:true,dashboards:true,reports:true,ai:false,clientPortal:false,api:false},limits:{clients:3,users:3,integrationsPerClient:3,reportsPerMonth:10,storageGb:1,syncFrequencyMinutes:1440,dataRetentionDays:90,aiRequestsPerMonth:0}},featureFlags:{platform_core_v2:{enabled:true,config:{},description:'Expanded workspace context'}},preferences:{language:'ru',timezone:'Asia/Almaty',theme:'system',settings:{}},recentItems:[],mode:'demo'};
export function getDemoBootstrap(activeAgencyId?:string|null,activeClientId?:string|null):WorkspaceBootstrap{const copy=structuredClone(demo);if(activeAgencyId&&activeAgencyId!==copy.activeAgency?.id)copy.activeAgency=copy.agencies.find(item=>item.id===activeAgencyId)??copy.activeAgency;if(activeClientId&&copy.clients.some(item=>item.id===activeClientId))copy.activeClientId=activeClientId;return copy}
