begin;

insert into public.integrations(slug,name,category,auth_type,is_beta,is_new,is_popular,lifecycle,sort_order) values
('ai-tracker','AI Tracker','analytics','api_key',true,true,false,'beta',10),
('activecampaign','ActiveCampaign','email','oauth2',false,false,false,'planned',20),
('adroll','AdRoll','paid_ads','oauth2',false,false,false,'planned',30),
('adform','Adform','paid_ads','oauth2',false,false,false,'planned',40),
('ahrefs','Ahrefs','seo','api_key',false,false,true,'planned',50),
('amazon-ads','Amazon Ads','paid_ads','oauth2',false,false,true,'planned',60),
('amazon-redshift','Amazon Redshift','database','basic',false,false,false,'planned',70),
('avanser','Avanser','call_tracking','api_key',false,false,false,'planned',80),
('backlink-manager','Backlink Manager','seo','api_key',false,false,false,'planned',90),
('basis-platform','Basis Platform','paid_ads','oauth2',false,false,false,'planned',100),
('basis-standalone-dsp','Basis Standalone DSP','paid_ads','oauth2',false,false,false,'planned',110),
('bigcommerce','BigCommerce','ecommerce','oauth2',false,false,false,'planned',120),
('bing-webmaster-tools','Bing Webmaster Tools','seo','oauth2',false,false,false,'planned',130),
('birdeye','BirdEye','local','api_key',false,false,false,'planned',140),
('brevo','Brevo','email','api_key',false,false,false,'planned',150),
('brightlocal','BrightLocal','local','api_key',false,false,false,'planned',160),
('ctm','CTM','call_tracking','api_key',false,false,false,'planned',170),
('callrail','CallRail','call_tracking','oauth2',false,false,true,'planned',180),
('callsource','CallSource','call_tracking','api_key',false,false,false,'planned',190),
('campaign-monitor','Campaign Monitor','email','oauth2',false,false,false,'planned',200),
('choozle','Choozle','paid_ads','api_key',false,false,false,'planned',210),
('constant-contact','Constant Contact','email','oauth2',false,false,false,'planned',220),
('delacon','Delacon','call_tracking','api_key',false,false,false,'planned',230),
('drip','Drip','email','api_key',false,false,false,'planned',240),
('facebook','Facebook','social','oauth2',false,false,true,'planned',250),
('gatherup','GatherUp','local','api_key',false,false,false,'planned',260),
('google-ad-manager','Google Ad Manager','paid_ads','oauth2',false,false,false,'planned',270),
('google-ads','Google Ads','paid_ads','oauth2',false,true,true,'beta',280),
('ga4','Google Analytics 4','analytics','oauth2',false,true,true,'beta',290),
('google-bigquery','Google BigQuery','database','oauth2',false,false,false,'planned',300),
('google-business-profile','Google Business Profile','local','oauth2',false,false,true,'planned',310),
('google-display-video-360','Google Display & Video 360','paid_ads','oauth2',false,false,false,'planned',320),
('google-lighthouse','Google Lighthouse','seo','api_key',false,false,false,'planned',330),
('google-local-services-ads','Google Local Services Ads','paid_ads','oauth2',false,false,false,'planned',340),
('google-pagespeed','Google PageSpeed','seo','api_key',false,false,false,'planned',350),
('search-console','Google Search Console','seo','oauth2',false,true,true,'beta',360),
('google-sheets','Google Sheets','analytics','oauth2',false,false,true,'planned',370),
('grade-us','Grade.us','local','api_key',false,false,false,'planned',380),
('gravity-forms','Gravity Forms','analytics','api_key',false,false,false,'planned',390),
('groundtruth','GroundTruth','paid_ads','api_key',false,false,false,'planned',400),
('highlevel','HighLevel','analytics','oauth2',false,false,true,'planned',410),
('hubspot','HubSpot','analytics','oauth2',false,false,true,'planned',420),
('instagram','Instagram','social','oauth2',false,false,true,'planned',430),
('keap','Keap','email','oauth2',false,false,false,'planned',440),
('kit','Kit','email','oauth2',false,false,false,'planned',450),
('klaviyo','Klaviyo','email','api_key',false,false,true,'planned',460),
('linkedin','LinkedIn','social','oauth2',false,false,false,'planned',470),
('linkedin-ads','LinkedIn Ads','paid_ads','oauth2',false,false,true,'planned',480),
('mailchimp','MailChimp','email','oauth2',false,false,true,'planned',490),
('majestic','Majestic','seo','api_key',false,false,false,'planned',500),
('marchex','Marchex','call_tracking','api_key',false,false,false,'planned',510),
('matomo','Matomo','analytics','api_key',false,false,false,'planned',520),
('meta-ads','Meta Ads','paid_ads','oauth2',false,true,true,'beta',530),
('microsoft-advertising','Microsoft Advertising','paid_ads','oauth2',false,false,true,'planned',540),
('microsoft-clarity','Microsoft Clarity','analytics','oauth2',false,false,false,'planned',550),
('moz','Moz','seo','api_key',false,false,false,'planned',560),
('mysql','MySQL','database','basic',false,false,false,'planned',570),
('pinterest','Pinterest','social','oauth2',false,false,false,'planned',580),
('pinterest-ads','Pinterest Ads','paid_ads','oauth2',false,false,false,'planned',590),
('postgresql','PostgreSQL','database','basic',false,false,false,'planned',600),
('rank-tracker','Rank Tracker','seo','api_key',false,true,true,'beta',610),
('reddit-ads','Reddit Ads','paid_ads','oauth2',false,false,false,'planned',620),
('se-ranking','SE Ranking','seo','api_key',false,false,true,'planned',630),
('salesforce','Salesforce','analytics','oauth2',false,false,true,'planned',640),
('semrush-backlinks','Semrush Backlinks','seo','api_key',false,false,true,'planned',650),
('semrush-projects','Semrush Projects','seo','api_key',false,false,true,'planned',660),
('sharpspring','SharpSpring','email','api_key',false,false,false,'planned',670),
('shopify','Shopify','ecommerce','oauth2',false,false,true,'planned',680),
('simpli-fi','Simpli.fi','paid_ads','api_key',false,false,false,'planned',690),
('snapchat-ads','Snapchat Ads','paid_ads','oauth2',false,false,false,'planned',700),
('snowflake','Snowflake','database','basic',false,false,false,'planned',710),
('spotify-ads','Spotify Ads','paid_ads','oauth2',false,false,false,'planned',720),
('stackadapt','StackAdapt','paid_ads','api_key',false,false,false,'planned',730),
('stripe','Stripe','ecommerce','oauth2',false,false,true,'planned',740),
('synup','Synup','local','api_key',false,false,false,'planned',750),
('tiktok','TikTok','social','oauth2',false,false,true,'planned',760),
('tiktok-ads','TikTok Ads','paid_ads','oauth2',false,true,true,'beta',770),
('trustpilot','Trustpilot','local','api_key',false,false,true,'planned',780),
('twilio','Twilio','call_tracking','api_key',false,false,true,'planned',790),
('unbounce','Unbounce','analytics','oauth2',false,false,false,'planned',800),
('vendasta','Vendasta','local','api_key',false,false,false,'planned',810),
('vimeo','Vimeo','social','oauth2',false,false,false,'planned',820),
('whatconverts','WhatConverts','call_tracking','api_key',false,false,true,'planned',830),
('wildjar','WildJar','call_tracking','api_key',false,false,false,'planned',840),
('woocommerce','WooCommerce','ecommerce','api_key',false,false,true,'planned',850),
('x-ads','X Ads','paid_ads','oauth2',false,false,false,'planned',860),
('yelp','Yelp','local','oauth2',false,false,false,'planned',870),
('yelp-ads','Yelp Ads','paid_ads','oauth2',false,false,false,'planned',880),
('yext','Yext','local','api_key',false,false,false,'planned',890),
('youtube','YouTube','social','oauth2',false,false,true,'planned',900)
on conflict (slug) do update set name=excluded.name,category=excluded.category,auth_type=excluded.auth_type,is_beta=excluded.is_beta,is_new=excluded.is_new,is_popular=excluded.is_popular,lifecycle=excluded.lifecycle,sort_order=excluded.sort_order;

insert into public.metric_dictionary(metric_key,label,description,data_type,aggregation,format,is_derived,formula,dependencies,category) values
('backlinks','Backlinks','Backlink count','int','last','integer',false,null,'{}','seo'),
('bounce_rate','Bounce Rate','Share of bounced sessions','percent','weighted','percent',false,null,'{}','analytics'),
('calls','Calls','Tracked calls','int','sum','integer',false,null,'{}','call_tracking'),
('clicks','Clicks','Number of clicks','int','sum','integer',false,null,'{}','engagement'),
('conversions','Conversions','Primary conversions','float','sum','decimal',false,null,'{}','conversion'),
('cpa','CPA','Spend divided by conversions','currency','derived','currency',true,'spend / nullif(conversions, 0)','{spend,conversions}','efficiency'),
('cpc','CPC','Spend divided by clicks','currency','derived','currency',true,'spend / nullif(clicks, 0)','{spend,clicks}','efficiency'),
('cpm','CPM','Spend per 1000 impressions','currency','derived','currency',true,'spend * 1000 / nullif(impressions, 0)','{spend,impressions}','efficiency'),
('ctr','CTR','Clicks divided by impressions','percent','derived','percent',true,'clicks / nullif(impressions, 0)','{clicks,impressions}','efficiency'),
('followers','Followers','Follower count','int','last','integer',false,null,'{}','social'),
('impressions','Impressions','Number of ad or content impressions','int','sum','integer',false,null,'{}','reach'),
('leads','Leads','Qualified lead actions','float','sum','decimal',false,null,'{}','conversion'),
('orders','Orders','Order count','int','sum','integer',false,null,'{}','ecommerce'),
('position','Average Position','Average search position','float','weighted','decimal',false,null,'{}','seo'),
('rating','Rating','Average rating','float','weighted','decimal',false,null,'{}','local'),
('results','Results','Provider-defined results','float','sum','decimal',false,null,'{}','conversion'),
('revenue','Revenue','Attributed revenue','currency','sum','currency',false,null,'{}','revenue'),
('reviews','Reviews','Review count','int','last','integer',false,null,'{}','local'),
('roas','ROAS','Revenue divided by spend','float','derived','ratio',true,'revenue / nullif(spend, 0)','{revenue,spend}','efficiency'),
('sessions','Sessions','Analytics sessions','int','sum','integer',false,null,'{}','analytics'),
('spend','Spend','Advertising spend','currency','sum','currency',false,null,'{}','cost'),
('users','Users','Analytics users','int','sum','integer',false,null,'{}','analytics'),
('video_views','Video Views','Provider video views','int','sum','integer',false,null,'{}','engagement')
on conflict (metric_key) do update set label=excluded.label,description=excluded.description,data_type=excluded.data_type,aggregation=excluded.aggregation,format=excluded.format,is_derived=excluded.is_derived,formula=excluded.formula,dependencies=excluded.dependencies,category=excluded.category;

insert into public.provider_metric_mappings(integration_id,provider_key,metric_key,transform)
select i.id,v.provider_key,v.metric_key,v.transform
from (values
('ga4','bounceRate','bounce_rate','{}'::jsonb),
('ga4','eventCount','results','{}'::jsonb),
('ga4','sessions','sessions','{}'::jsonb),
('ga4','totalUsers','users','{}'::jsonb),
('google-ads','metrics.clicks','clicks','{}'::jsonb),
('google-ads','metrics.conversions','conversions','{}'::jsonb),
('google-ads','metrics.conversions_value','revenue','{}'::jsonb),
('google-ads','metrics.cost_micros','spend','{}'::jsonb),
('google-ads','metrics.impressions','impressions','{}'::jsonb),
('meta-ads','action_values.purchase','revenue','{}'::jsonb),
('meta-ads','actions.lead','leads','{}'::jsonb),
('meta-ads','clicks','clicks','{}'::jsonb),
('meta-ads','impressions','impressions','{}'::jsonb),
('meta-ads','spend','spend','{}'::jsonb),
('search-console','clicks','clicks','{}'::jsonb),
('search-console','impressions','impressions','{}'::jsonb),
('search-console','position','position','{}'::jsonb),
('tiktok-ads','clicks','clicks','{}'::jsonb),
('tiktok-ads','conversion','conversions','{}'::jsonb),
('tiktok-ads','impressions','impressions','{}'::jsonb),
('tiktok-ads','spend','spend','{}'::jsonb),
('tiktok-ads','video_play_actions','video_views','{}'::jsonb)
) as v(integration_slug,provider_key,metric_key,transform)
join public.integrations i on i.slug=v.integration_slug
on conflict (integration_id,provider_key) do update set metric_key=excluded.metric_key,transform=excluded.transform;

commit;
